#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Applies the CCCS/NSA/CISA hardening baseline to a Windows workstation or server.

.DESCRIPTION
    Recommended starting point for Canadian organizations, government contractors,
    healthcare providers, and any organization operating under CCCS, Protected B,
    or CPCSC requirements. Based on CSE/CCCS ITSP.70.012 and NSA/CISA guidance.

.NOTES
    ================================================================
    Study Workstation Configurator
    Template: CCCS / NSA / CISA Hardening Baseline

    Generated by Hans Study, CISSP / TSG Labs
    Generated:          2026-05-16
    Config fingerprint: (curated baseline; not configurator output)

    Website:   https://hans.study
    Email:     contact@hans.study
    LinkedIn:  https://linkedin.com/in/hans-study
    Instagram: https://instagram.com/studybyt3s
    X:         https://x.com/studybyt3s
    YouTube:   https://youtube.com/@studybyt3s
    GitHub:    https://github.com/tsglabs

    Target OS:  Windows 10/11 Pro or Enterprise
                Windows Server 2019/2022/2025
    Version:    2.0

    STANDARDS REFERENCED:
      CSE/CCCS ITSP.70.012 Hardening Microsoft Windows 10 (cyber.gc.ca)
      NSA/CISA Cybersecurity Information Sheets           (media.defense.gov)
      NSA/CISA Keeping PowerShell Security Measures (June 2022)
      DISA STIG Windows 11 V2R2                    (public.cyber.mil)
      CIS Microsoft Windows 11 Benchmark v3.0       (cisecurity.org)

    Source-available. Personal and internal use permitted.
    Redistribution requires written authorization from Hans Study.
    See LICENSE for full terms.
    Test in a non-production environment before deployment.
    Hans Study accepts no liability for unintended consequences.
    ================================================================
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = "Continue"
$SkippedEntControls = [System.Collections.Generic.List[string]]::new()

$LogDate = Get-Date -Format "yyyyMMdd"
$LogPath = "C:\Logs\CCCS-NSA-CISA-Baseline_$LogDate.log"
if (-not (Test-Path "C:\Logs")) { New-Item -ItemType Directory -Path "C:\Logs" -Force | Out-Null }
Start-Transcript -Path $LogPath -Append -IncludeInvocationHeader | Out-Null
# ── HELPER FUNCTIONS ──────────────────────────────────────────────────────────
# These functions are embedded in each script so it runs
# standalone without any module dependency.

# Write-TSGSection: prints a visible section header to the console and transcript
function Write-TSGSection {
    param([string]$Title, [string]$Subtitle = "")
    Write-Host ""
    Write-Host "  ======================================================================" -ForegroundColor DarkGray
    Write-Host "  $Title" -ForegroundColor Yellow
    if ($Subtitle) { Write-Host "  $Subtitle" -ForegroundColor DarkGray }
    Write-Host "  ======================================================================" -ForegroundColor DarkGray
}

# Set-TSGRegistry: idempotent registry write -- creates the key path if missing,
# sets the value, and logs OK or FAIL for every entry. Safe to re-run.
function Set-TSGRegistry {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$Name,
        [Parameter(Mandatory)][object]$Value,
        [ValidateSet("DWord","QWord","String","ExpandString","Binary","MultiString")]
        [string]$Type = "DWord"
    )
    try {
        if (-not (Test-Path $Path)) { New-Item -Path $Path -Force -ErrorAction Stop | Out-Null }
        Set-ItemProperty -Path $Path -Name $Name -Value $Value -Type $Type -Force -ErrorAction Stop
        Write-Host "    [OK] $($Path.Split('\')[-1])\$Name = $Value" -ForegroundColor Green
    } catch {
        Write-Host "    [FAIL] $Name at $Path" -ForegroundColor Red
        Write-Host "           $($_.Exception.Message)" -ForegroundColor DarkGray
    }
}

# Remove-TSGAppx: removes an AppX package for all existing users and prevents
# reinstall for future accounts. Handles missing packages without errors.
function Remove-TSGAppx {
    param([Parameter(Mandatory)][string]$PackageName, [Parameter(Mandatory)][string]$FriendlyName)
    Write-Host "    Removing: $FriendlyName ($PackageName)" -ForegroundColor DarkGray
    try {
        Get-AppxProvisionedPackage -Online -ErrorAction SilentlyContinue |
            Where-Object { $_.DisplayName -like "*$PackageName*" } |
            Remove-AppxProvisionedPackage -Online -ErrorAction SilentlyContinue | Out-Null
        Get-AppxPackage -AllUsers -ErrorAction SilentlyContinue |
            Where-Object { $_.Name -like "*$PackageName*" } |
            Remove-AppxPackage -AllUsers -ErrorAction SilentlyContinue
        Write-Host "    [OK] $FriendlyName removed or already absent" -ForegroundColor Green
    } catch { Write-Host "    [SKIP] $FriendlyName -- $($_.Exception.Message)" -ForegroundColor DarkGray }
}

# Test-TSGEnterprise: checks the OS SKU and gates Enterprise-only controls.
# Credential Guard and AppLocker enforcement require Enterprise or Education.
# Returns $true on Enterprise/Server, $false on Pro with a logged warning.
# Source: learn.microsoft.com/en-us/windows/security/licensing-and-edition-requirements
function Test-TSGEnterprise {
    param([string]$ControlName = "This control")
    $sku = (Get-CimInstance Win32_OperatingSystem -ErrorAction Stop).OperatingSystemSKU
    # Enterprise=4, Enterprise N=27, Enterprise Eval=70, Enterprise N Eval=84,
    # Enterprise G=125, Education=4, Server variants=161-172
    if ($sku -in @(4,27,70,84,125,161,162,163,164,169,170,171,172)) { return $true }
    Write-Host "    [SKIP] $ControlName requires Enterprise or Education license (SKU: $sku)" -ForegroundColor Yellow
    Write-Host "           Source: learn.microsoft.com/windows/security/licensing-and-edition-requirements" -ForegroundColor DarkGray
    $script:SkippedEntControls.Add($ControlName)
    return $false
}

# New-TSGRestorePoint: creates a System Restore point before hardening.
# Can fail on domain machines with Group Policy restrictions -- not fatal.
function New-TSGRestorePoint {
    param([string]$Description = "Hardening Script")
    Write-Host "  Creating system restore point..." -ForegroundColor DarkGray
    try {
        Checkpoint-Computer -Description "$Description $(Get-Date -Format 'yyyy-MM-dd HH:mm')" `
            -RestorePointType "MODIFY_SETTINGS" -ErrorAction Stop
        Write-Host "  [OK] Restore point created" -ForegroundColor Green
    } catch {
        Write-Host "  [WARN] Restore point failed -- continuing ($($_.Exception.Message))" -ForegroundColor Yellow
    }
}

# Disable-TSGNetBIOS: disables NetBIOS over TCP/IP on all IPv4 adapters.
# Uses WMI because there is no native PowerShell cmdlet for this.
# SetTcpipNetbios(2) = disable. Value 1 = enable. Value 0 = use DHCP setting.
function Disable-TSGNetBIOS {
    Write-Host "    Disabling NetBIOS over TCP/IP on all adapters..." -ForegroundColor DarkGray
    try {
        $adapters = Get-WmiObject -Class Win32_NetworkAdapterConfiguration `
            -Filter "IPEnabled = True" -ErrorAction Stop
        $count = 0
        foreach ($adapter in $adapters) {
            $result = $adapter.SetTcpipNetbios(2)
            if ($result.ReturnValue -eq 0) { $count++ }
        }
        Write-Host "    [OK] NetBIOS disabled on $count adapter(s)" -ForegroundColor Green
    } catch { Write-Host "    [FAIL] NetBIOS disable -- $($_.Exception.Message)" -ForegroundColor Red }
}

Write-Host ""
Write-Host "  =========================================================" -ForegroundColor Cyan
Write-Host "  CCCS / NSA / CISA Hardening Baseline" -ForegroundColor Cyan
Write-Host "  CSE/CCCS ITSP.70.012 + NSA/CISA guidance" -ForegroundColor White
Write-Host "  Hans Study, CISSP | https://hans.study" -ForegroundColor DarkGray
Write-Host "  Log: $LogPath" -ForegroundColor DarkGray
Write-Host "  =========================================================" -ForegroundColor Cyan
Write-Host ""

$OsSku = (Get-CimInstance Win32_OperatingSystem).OperatingSystemSKU
$IsEnterprise = $OsSku -in @(4,27,70,84,125,161,162,163,164,169,170,171,172)
Write-Host "  OS SKU: $OsSku | Edition: $(if ($IsEnterprise) { 'Enterprise/Server' } else { 'Pro' })" `
    -ForegroundColor $(if ($IsEnterprise) { "Green" } else { "Yellow" })
Write-Host ""

New-TSGRestorePoint -Description "CCCS / NSA / CISA Baseline"


# ════════════════════════════════════════════════════════════════════════════════
# CREDENTIAL AND IDENTITY PROTECTION
# CCCS ITSP.70.012 addresses credential protection as a primary category.
# WDigest removal and NTLMv2 enforcement are non-negotiable per CCCS guidance.
# ════════════════════════════════════════════════════════════════════════════════
Write-TSGSection "CREDENTIAL AND IDENTITY PROTECTION" "CCCS ITSP.70.012 | DISA WN11-CC-000040/SO-000100/195"

# Disable WDigest -- prevents cleartext credentials in LSASS memory
# Source: DISA WN11-CC-000040 | CIS 18.9.29.1 | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\WDigest" -Name "UseLogonCredential" -Value 0

# Do not store LAN Manager hash
# Source: DISA WN11-SO-000190 | CIS 2.3.11.6 | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Lsa" -Name "NoLMHash" -Value 1

# Require NTLMv2 only -- LmCompatibilityLevel 5 refuses all LM and NTLMv1
# Source: DISA WN11-SO-000195 | CIS 2.3.11.7 | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Lsa" -Name "LmCompatibilityLevel" -Value 5

# Enable LSA Protection (RunAsPPL) -- works on all editions, restart required
# Source: DISA WN11-SO-000100 | CIS 18.3.2 | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Lsa" -Name "RunAsPPL" -Value 1
Write-Host "    [NOTE] Restart required for LSA Protection" -ForegroundColor Yellow

# Credential Guard -- Enterprise/Education only
# Source: DISA WN11-00-000095 | NSA/CISA | CCCS ITSP.70.012
if (Test-TSGEnterprise -ControlName "Credential Guard") {
    Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\DeviceGuard" -Name "EnableVirtualizationBasedSecurity" -Value 1
    Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\DeviceGuard" -Name "RequirePlatformSecurityFeatures" -Value 3
    Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\DeviceGuard\Scenarios\CredentialGuard" -Name "Enabled" -Value 1
    Write-Host "    [NOTE] Restart required for Credential Guard" -ForegroundColor Yellow
}


# ════════════════════════════════════════════════════════════════════════════════
# NETWORK HARDENING
# CCCS ITSP.70.012 explicitly requires LLMNR disable and SMBv1 removal.
# NSA/CISA June 2022 CSI explicitly requires PowerShell v2 removal.
# ════════════════════════════════════════════════════════════════════════════════
Write-TSGSection "NETWORK HARDENING" "CCCS ITSP.70.012 | DISA WN11-00-000155/160/165 | NSA/CISA"

# Disable SMBv1 -- EternalBlue vector, no modern system requires it
# Source: DISA WN11-00-000160/165 | CIS 18.3.3 | NSA | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters" -Name "SMB1" -Value 0
Disable-WindowsOptionalFeature -Online -FeatureName "SMB1Protocol" -NoRestart -ErrorAction SilentlyContinue | Out-Null
Write-Host "    [OK] SMBv1 disabled" -ForegroundColor Green

# Remove PowerShell v2 -- bypasses AMSI and all modern PS security features
# Source: DISA WN11-00-000155 | NSA/CISA June 2022 CSI | CCCS ITSP.70.012
Disable-WindowsOptionalFeature -Online -FeatureName "MicrosoftWindowsPowerShellV2Root" -NoRestart -ErrorAction SilentlyContinue | Out-Null
Write-Host "    [OK] PowerShell v2 engine removed" -ForegroundColor Green

# Disable LLMNR -- passive NTLMv2 hash capture vector
# Source: DISA WN11-CC-000085 | CIS 18.5.4 | NSA/CISA | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient" -Name "EnableMulticast" -Value 0

# Disable NetBIOS over TCP/IP
# Source: DISA WN11-CC-000080 | NSA | CCCS ITSP.70.012
Disable-TSGNetBIOS

# Windows Firewall -- enable all profiles, default-deny inbound
# Source: DISA WN11-NX-000010/015/020/025/030/035 | CIS 9.x | CCCS ITSP.70.012
Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled True
Set-NetFirewallProfile -Profile Domain,Public,Private -DefaultInboundAction Block
Write-Host "    [OK] Firewall enabled, default-deny inbound" -ForegroundColor Green

# Require SMB packet signing on client and server
# Source: DISA WN11-SO-000160/165 | CIS 2.3.9.1/2.3.9.2 | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters" -Name "RequireSecuritySignature" -Value 1
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters" -Name "RequireSecuritySignature" -Value 1


# ════════════════════════════════════════════════════════════════════════════════
# WINDOWS DEFENDER
# ════════════════════════════════════════════════════════════════════════════════
Write-TSGSection "WINDOWS DEFENDER" "DISA WN11-00-000270/275"

Set-Service -Name "WinDefend" -StartupType Automatic -ErrorAction SilentlyContinue
Start-Service -Name "WinDefend" -ErrorAction SilentlyContinue
Set-MpPreference -DisableRealtimeMonitoring $false
Set-MpPreference -EnableNetworkProtection Enabled
Write-Host "    [OK] Defender running with network protection" -ForegroundColor Green


# ════════════════════════════════════════════════════════════════════════════════
# AUDIT POLICY AND LOGGING
# CCCS ITSP.70.012 includes a dedicated section on audit logging requirements.
# NSA/CISA explicitly recommend Script Block Logging and PS Transcription.
# ════════════════════════════════════════════════════════════════════════════════
Write-TSGSection "AUDIT POLICY AND LOGGING" "CCCS ITSP.70.012 | DISA WN11-AU | NSA/CISA June 2022 CSI"

# Core audit categories -- all verified auditpol subcategory names
AuditPol /set /subcategory:"Logon"               /success:enable /failure:enable | Out-Null
AuditPol /set /subcategory:"Logoff"              /success:enable                 | Out-Null
AuditPol /set /subcategory:"Account Lockout"     /failure:enable                 | Out-Null
AuditPol /set /subcategory:"Credential Validation" /success:enable /failure:enable | Out-Null
AuditPol /set /subcategory:"Process Creation"    /success:enable                 | Out-Null
AuditPol /set /subcategory:"Sensitive Privilege Use" /success:enable /failure:enable | Out-Null
AuditPol /set /subcategory:"Audit Policy Change" /success:enable /failure:enable | Out-Null
Write-Host "    [OK] Audit policy configured" -ForegroundColor Green

# Process creation with command-line capture -- requires both auditpol and registry key
# Source: DISA WN11-AU-000500/505 | NSA | CCCS ITSP.70.012
Set-TSGRegistry `
    -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Audit" `
    -Name "ProcessCreationIncludeCmdLine_Enabled" `
    -Value 1

# Increase event log sizes -- default 64MB Security log fills in hours
# Source: DISA WN11-AU-000045 | CIS 18.9.26.1 | CCCS ITSP.70.012
wevtutil sl Security    /ms:1073741824 | Out-Null   # 1 GB
wevtutil sl Application /ms:268435456  | Out-Null   # 256 MB
wevtutil sl System      /ms:268435456  | Out-Null   # 256 MB
Write-Host "    [OK] Log sizes: Security 1GB, Application/System 256MB" -ForegroundColor Green

# PowerShell Script Block Logging -- NSA/CISA explicitly recommend this
# Source: DISA WN11-CC-000315 | NSA/CISA June 2022 CSI | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging" -Name "EnableScriptBlockLogging" -Value 1
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging" -Name "EnableScriptBlockInvocationLogging" -Value 1
wevtutil sl "Microsoft-Windows-PowerShell/Operational" /ms:104857600 | Out-Null
Write-Host "    [OK] PowerShell Script Block Logging enabled" -ForegroundColor Green

# PowerShell Transcription -- records all PS input/output to log files
# Source: NSA/CISA June 2022 CSI | CCCS | DISA WN11-CC-000326
$transcriptPath = "C:\Logs\PSTranscripts"
if (-not (Test-Path $transcriptPath)) { New-Item -ItemType Directory -Path $transcriptPath -Force | Out-Null }
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\Transcription" -Name "EnableTranscripting"    -Value 1
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\Transcription" -Name "OutputDirectory"        -Value $transcriptPath -Type String
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\Transcription" -Name "EnableInvocationHeader" -Value 1
Write-Host "    [OK] PS Transcription enabled -- output to $transcriptPath" -ForegroundColor Green


# ════════════════════════════════════════════════════════════════════════════════
# ACCESS CONTROL
# ════════════════════════════════════════════════════════════════════════════════
Write-TSGSection "ACCESS CONTROL" "DISA WN11-SO-000245/251 | CIS 2.3.17 | CCCS ITSP.70.012"

# UAC enabled -- standard prompt level (not Always Notify)
# Source: DISA WN11-SO-000245 | CIS 2.3.17.1 | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" -Name "EnableLUA"                    -Value 1
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" -Name "PromptOnSecureDesktop"         -Value 1
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" -Name "ConsentPromptBehaviorAdmin"    -Value 1

# Disable AutoRun on all drive types
# Source: DISA WN11-CC-000150 | CIS 18.9.8.1 | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer" -Name "NoDriveTypeAutoRun" -Value 255
Set-TSGRegistry -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer" -Name "NoDriveTypeAutoRun" -Value 255

# Require NLA for RDP connections (UserAuthentication = 1)
# Source: DISA WN11-CC-000030 | CIS 18.9.59.2.1 | CCCS
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "UserAuthentication" -Value 1

# Restrict PowerShell execution policy to RemoteSigned
# Source: NSA/CISA June 2022 CSI | CCCS ITSP.70.012
Set-ExecutionPolicy RemoteSigned -Scope LocalMachine -Force
Write-Host "    [OK] PS ExecutionPolicy set to RemoteSigned" -ForegroundColor Green

# Block Office macros from internet sources
# Source: DISA STIG | CIS | CCCS ITSP.70.012
$officeVersion = "16.0"
foreach ($app in @("Word", "Excel", "PowerPoint", "Outlook", "Access")) {
    Set-TSGRegistry -Path "HKCU:\SOFTWARE\Policies\Microsoft\Office\$officeVersion\$app\Security" -Name "VBAWarnings" -Value 4
}
Write-Host "    [OK] Office macros blocked from internet sources" -ForegroundColor Green


# ════════════════════════════════════════════════════════════════════════════════
# TELEMETRY AND PRIVACY
# ════════════════════════════════════════════════════════════════════════════════
Write-TSGSection "TELEMETRY AND PRIVACY" "DISA WN11-CC-000206/225 | CIS 18.9.16/44/46 | CCCS ITSP.70.012"

# Disable DiagTrack (telemetry service)
# Source: DISA WN11-CC-000206 | CIS 18.9.16.1 | CCCS ITSP.70.012
# AllowTelemetry = 0 (Security level). Note: Pro enforces minimum level 1
# (Basic). Level 0 enforcement requires Enterprise or Server.
Stop-Service -Name "DiagTrack" -ErrorAction SilentlyContinue
Set-Service  -Name "DiagTrack" -StartupType Disabled
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection" -Name "AllowTelemetry" -Value 0
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection" -Name "AllowTelemetry" -Value 0
if (-not $IsEnterprise) {
    Write-Host "    [NOTE] On Pro, telemetry minimum is level 1 (Basic). Enterprise enforces level 0." -ForegroundColor Yellow
}

# Disable Activity History and Windows Timeline
# Source: DISA WN11-CC-000225 | CIS 18.9.46.1
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\System" -Name "PublishUserActivities" -Value 0
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\System" -Name "UploadUserActivities"  -Value 0

# Disable Windows Recall -- AI screenshot indexing
# Source: NSA/CISA | CCCS | PIPEDA (Canada)
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsAI" -Name "DisableAIDataAnalysis" -Value 1
Set-TSGRegistry -Path "HKCU:\SOFTWARE\Policies\Microsoft\Windows\WindowsAI" -Name "DisableAIDataAnalysis" -Value 1
Disable-WindowsOptionalFeature -Online -FeatureName "Recall" -NoRestart -ErrorAction SilentlyContinue | Out-Null

# Disable Advertising ID
# Source: DISA WN11-CC-000010 | CIS 18.9.44.1
Set-TSGRegistry -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\AdvertisingInfo" -Name "Enabled" -Value 0

Write-Host "    [OK] Telemetry, Activity History, Recall, Advertising ID disabled" -ForegroundColor Green


# ════════════════════════════════════════════════════════════════════════════════
# EXPLOIT MITIGATION
# ════════════════════════════════════════════════════════════════════════════════
Write-TSGSection "EXPLOIT MITIGATION" "DISA WN11-00-000020/025 | CIS 18.8.21.5 | NSA | CCCS ITSP.70.012"

# DEP AlwaysOn -- marks data memory pages non-executable, restart required
# Source: DISA WN11-00-000020 | CIS 18.8.21.5 | NSA | CCCS ITSP.70.012
bcdedit /set nx AlwaysOn | Out-Null
Write-Host "    [OK] DEP set to AlwaysOn (restart required)" -ForegroundColor Green

# ASLR with forced relocation -- randomizes module base addresses
# Source: CIS | NSA | CCCS ITSP.70.012
Set-ProcessMitigation -System -Enable ASLR,ForceRelocateImages -ErrorAction SilentlyContinue
Write-Host "    [OK] ASLR and forced relocation enabled" -ForegroundColor Green

# SEHOP -- validates exception handler chain before dispatching
# Source: DISA WN11-00-000025 | CIS | CCCS ITSP.70.012
# Value = 0 ENABLES SEHOP (counterintuitive registry name, confirmed correct)
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\kernel" -Name "DisableExceptionChainValidation" -Value 0

# Disable hibernation -- hiberfil.sys can contain credentials at rest
# Source: NSA | CCCS ITSP.70.012
powercfg -h off
Write-Host "    [OK] Hibernation disabled, hiberfil.sys removed" -ForegroundColor Green


# ════════════════════════════════════════════════════════════════════════════════
# FINALIZATION
# ════════════════════════════════════════════════════════════════════════════════
Write-TSGSection "FINALIZATION"

if ($SkippedEntControls.Count -gt 0) {
    Write-Host ""
    Write-Host "  Enterprise-only controls skipped on this Pro SKU:" -ForegroundColor Yellow
    $SkippedEntControls | ForEach-Object { Write-Host "    * $_" -ForegroundColor Yellow }
}

Write-Host ""
Write-Host "  CCCS / NSA / CISA baseline applied." -ForegroundColor Cyan
Write-Host "  Log: $LogPath" -ForegroundColor White
Write-Host "  RESTART REQUIRED: DEP, LSA Protection, Credential Guard" -ForegroundColor Yellow
Write-Host "  Hans Study | https://hans.study | contact@hans.study" -ForegroundColor DarkGray

$restart = Read-Host "  Restart now? [y/N]"
if ($restart -match '^[Yy]') {
    Write-Host "  Restarting in 15 seconds. Press Ctrl+C to cancel." -ForegroundColor Yellow
    Start-Sleep -Seconds 15
    Restart-Computer -Force
}

Stop-Transcript | Out-Null
