#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Applies the DISA STIG hardening baseline to a Windows workstation or server.

.DESCRIPTION
    Addresses all CAT I (critical) and most CAT II (medium) DISA STIG findings
    for standalone, non-domain-joined Windows 10 and Windows 11 systems.
    The strictest commonly-used commercial hardening baseline.

    Be aware before deploying:
      UAC is set to Always Notify (max level, CAT II requirement WN11-SO-000251)
      RDP is disabled by default -- comment out the RDP block if remote access needed
      WSH is disabled -- will break any .vbs or .js automation in use
      AppLocker service is started on Enterprise -- rule configuration via GPO required

.NOTES
    ================================================================
    Study Workstation Configurator
    Template: DISA STIG Hardening Baseline

    Generated by Hans Study, CISSP / TSG Labs
    Generated:          2026-05-16
    Config fingerprint: (curated baseline; not configurator output)

    Website:   https://hans.study
    Email:     contact@hans.study
    LinkedIn:  https://linkedin.com/in/hans-study
    Instagram: https://instagram.com/studybyt3s
    X:         https://x.com/studybyt3s
    YouTube:   https://youtube.com/@studybyt3s
    GitHub:    https://github.com/tsglabs

    Target OS:  Windows 10/11 Pro or Enterprise, Server 2019/2022/2025
    Version:    2.0

    STANDARDS REFERENCED:
      DISA STIG Windows 11 V2R2 / Windows 10 V2R7 (public.cyber.mil)
      CIS Microsoft Windows 11 Benchmark v3.0      (cisecurity.org)
      NSA/CISA Cybersecurity Information Sheets    (media.defense.gov)
      CSE/CCCS ITSP.70.012                         (cyber.gc.ca)

    Source-available. Personal and internal use permitted.
    Redistribution requires written authorization from Hans Study.
    See LICENSE for full terms.
    Test in a non-production environment before deployment.
    Hans Study accepts no liability for unintended consequences.
    ================================================================
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = "Continue"
$SkippedEntControls = [System.Collections.Generic.List[string]]::new()

$LogDate = Get-Date -Format "yyyyMMdd"
$LogPath = "C:\Logs\DISA-STIG-Baseline_$LogDate.log"
if (-not (Test-Path "C:\Logs")) { New-Item -ItemType Directory -Path "C:\Logs" -Force | Out-Null }
Start-Transcript -Path $LogPath -Append -IncludeInvocationHeader | Out-Null
# ── HELPER FUNCTIONS ──────────────────────────────────────────────────────────
# These functions are embedded in each script so it runs
# standalone without any module dependency.

# Write-TSGSection: prints a visible section header to the console and transcript
function Write-TSGSection {
    param([string]$Title, [string]$Subtitle = "")
    Write-Host ""
    Write-Host "  ======================================================================" -ForegroundColor DarkGray
    Write-Host "  $Title" -ForegroundColor Yellow
    if ($Subtitle) { Write-Host "  $Subtitle" -ForegroundColor DarkGray }
    Write-Host "  ======================================================================" -ForegroundColor DarkGray
}

# Set-TSGRegistry: idempotent registry write -- creates the key path if missing,
# sets the value, and logs OK or FAIL for every entry. Safe to re-run.
function Set-TSGRegistry {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$Name,
        [Parameter(Mandatory)][object]$Value,
        [ValidateSet("DWord","QWord","String","ExpandString","Binary","MultiString")]
        [string]$Type = "DWord"
    )
    try {
        if (-not (Test-Path $Path)) { New-Item -Path $Path -Force -ErrorAction Stop | Out-Null }
        Set-ItemProperty -Path $Path -Name $Name -Value $Value -Type $Type -Force -ErrorAction Stop
        Write-Host "    [OK] $($Path.Split('\')[-1])\$Name = $Value" -ForegroundColor Green
    } catch {
        Write-Host "    [FAIL] $Name at $Path" -ForegroundColor Red
        Write-Host "           $($_.Exception.Message)" -ForegroundColor DarkGray
    }
}

# Remove-TSGAppx: removes an AppX package for all existing users and prevents
# reinstall for future accounts. Handles missing packages without errors.
function Remove-TSGAppx {
    param([Parameter(Mandatory)][string]$PackageName, [Parameter(Mandatory)][string]$FriendlyName)
    Write-Host "    Removing: $FriendlyName ($PackageName)" -ForegroundColor DarkGray
    try {
        Get-AppxProvisionedPackage -Online -ErrorAction SilentlyContinue |
            Where-Object { $_.DisplayName -like "*$PackageName*" } |
            Remove-AppxProvisionedPackage -Online -ErrorAction SilentlyContinue | Out-Null
        Get-AppxPackage -AllUsers -ErrorAction SilentlyContinue |
            Where-Object { $_.Name -like "*$PackageName*" } |
            Remove-AppxPackage -AllUsers -ErrorAction SilentlyContinue
        Write-Host "    [OK] $FriendlyName removed or already absent" -ForegroundColor Green
    } catch { Write-Host "    [SKIP] $FriendlyName -- $($_.Exception.Message)" -ForegroundColor DarkGray }
}

# Test-TSGEnterprise: checks the OS SKU and gates Enterprise-only controls.
# Credential Guard and AppLocker enforcement require Enterprise or Education.
# Returns $true on Enterprise/Server, $false on Pro with a logged warning.
# Source: learn.microsoft.com/en-us/windows/security/licensing-and-edition-requirements
function Test-TSGEnterprise {
    param([string]$ControlName = "This control")
    $sku = (Get-CimInstance Win32_OperatingSystem -ErrorAction Stop).OperatingSystemSKU
    # Enterprise=4, Enterprise N=27, Enterprise Eval=70, Enterprise N Eval=84,
    # Enterprise G=125, Education=4, Server variants=161-172
    if ($sku -in @(4,27,70,84,125,161,162,163,164,169,170,171,172)) { return $true }
    Write-Host "    [SKIP] $ControlName requires Enterprise or Education license (SKU: $sku)" -ForegroundColor Yellow
    Write-Host "           Source: learn.microsoft.com/windows/security/licensing-and-edition-requirements" -ForegroundColor DarkGray
    $script:SkippedEntControls.Add($ControlName)
    return $false
}

# New-TSGRestorePoint: creates a System Restore point before hardening.
# Can fail on domain machines with Group Policy restrictions -- not fatal.
function New-TSGRestorePoint {
    param([string]$Description = "Hardening Script")
    Write-Host "  Creating system restore point..." -ForegroundColor DarkGray
    try {
        Checkpoint-Computer -Description "$Description $(Get-Date -Format 'yyyy-MM-dd HH:mm')" `
            -RestorePointType "MODIFY_SETTINGS" -ErrorAction Stop
        Write-Host "  [OK] Restore point created" -ForegroundColor Green
    } catch {
        Write-Host "  [WARN] Restore point failed -- continuing ($($_.Exception.Message))" -ForegroundColor Yellow
    }
}

# Disable-TSGNetBIOS: disables NetBIOS over TCP/IP on all IPv4 adapters.
# Uses WMI because there is no native PowerShell cmdlet for this.
# SetTcpipNetbios(2) = disable. Value 1 = enable. Value 0 = use DHCP setting.
function Disable-TSGNetBIOS {
    Write-Host "    Disabling NetBIOS over TCP/IP on all adapters..." -ForegroundColor DarkGray
    try {
        $adapters = Get-WmiObject -Class Win32_NetworkAdapterConfiguration `
            -Filter "IPEnabled = True" -ErrorAction Stop
        $count = 0
        foreach ($adapter in $adapters) {
            $result = $adapter.SetTcpipNetbios(2)
            if ($result.ReturnValue -eq 0) { $count++ }
        }
        Write-Host "    [OK] NetBIOS disabled on $count adapter(s)" -ForegroundColor Green
    } catch { Write-Host "    [FAIL] NetBIOS disable -- $($_.Exception.Message)" -ForegroundColor Red }
}

Write-Host ""
Write-Host "  =========================================================" -ForegroundColor Cyan
Write-Host "  DISA STIG Hardening Baseline" -ForegroundColor Cyan
Write-Host "  Windows 11 V2R2 / Windows 10 V2R7 -- CAT I and CAT II" -ForegroundColor White
Write-Host "  Hans Study, CISSP | https://hans.study" -ForegroundColor DarkGray
Write-Host "  Log: $LogPath" -ForegroundColor DarkGray
Write-Host "  =========================================================" -ForegroundColor Cyan
Write-Host ""

$OsSku = (Get-CimInstance Win32_OperatingSystem).OperatingSystemSKU
$IsEnterprise = $OsSku -in @(4,27,70,84,125,161,162,163,164,169,170,171,172)
Write-Host "  OS SKU: $OsSku | Edition: $(if ($IsEnterprise) { 'Enterprise/Server' } else { 'Pro' })" `
    -ForegroundColor $(if ($IsEnterprise) { "Green" } else { "Yellow" })
Write-Host ""

New-TSGRestorePoint -Description "DISA STIG Baseline"


# ================================================================================
# CREDENTIAL AND IDENTITY PROTECTION
# Source: DISA WN11-CC-000040 | WN11-SO-000100/190/195 | WN11-00-000095
# ================================================================================
Write-TSGSection "CREDENTIAL AND IDENTITY PROTECTION" "DISA WN11-CC-000040 | WN11-SO-000100/190/195 | WN11-00-000095"

# Disable WDigest -- prevents cleartext credentials in LSASS memory
# DISA CAT II: WN11-CC-000040 | CIS 18.9.29.1 | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\WDigest" -Name "UseLogonCredential" -Value 0

# Do not store LAN Manager hash
# DISA CAT II: WN11-SO-000190 | CIS 2.3.11.6 | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Lsa" -Name "NoLMHash" -Value 1

# Require NTLMv2 only (LmCompatibilityLevel 5 = refuse all LM and NTLMv1)
# DISA CAT II: WN11-SO-000195 | CIS 2.3.11.7 | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Lsa" -Name "LmCompatibilityLevel" -Value 5

# Enable LSA Protection (RunAsPPL) -- all editions, restart required
# DISA CAT II: WN11-SO-000100 | CIS 18.3.2 | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Lsa" -Name "RunAsPPL" -Value 1
Write-Host "    [NOTE] Restart required for LSA Protection" -ForegroundColor Yellow

# Credential Guard -- Enterprise/Education only
# DISA CAT II: WN11-00-000095 | NSA/CISA | CCCS ITSP.70.012
if (Test-TSGEnterprise -ControlName "Credential Guard (WN11-00-000095)") {
    Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\DeviceGuard" -Name "EnableVirtualizationBasedSecurity" -Value 1
    Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\DeviceGuard" -Name "RequirePlatformSecurityFeatures" -Value 3
    Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\DeviceGuard\Scenarios\CredentialGuard" -Name "Enabled" -Value 1
    Write-Host "    [NOTE] Restart required for Credential Guard" -ForegroundColor Yellow
}


# ================================================================================
# NETWORK HARDENING
# Source: DISA WN11-00-000155/160/165 | WN11-CC-000080/085 | WN11-NX | WN11-SO-000160/165
# ================================================================================
Write-TSGSection "NETWORK HARDENING" "DISA WN11-00-000155/160/165 | WN11-CC-000080/085 | WN11-NX"

# Disable SMBv1 -- EternalBlue vector, DISA CAT I finding if present
# DISA CAT II: WN11-00-000160/165 | CIS 18.3.3 | NSA | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters" -Name "SMB1" -Value 0
Disable-WindowsOptionalFeature -Online -FeatureName "SMB1Protocol" -NoRestart -ErrorAction SilentlyContinue | Out-Null
Write-Host "    [OK] SMBv1 disabled -- WN11-00-000160/165" -ForegroundColor Green

# Remove PowerShell v2 -- bypasses AMSI and all modern PS security features
# DISA CAT II: WN11-00-000155 | NSA/CISA June 2022 CSI | CCCS ITSP.70.012
Disable-WindowsOptionalFeature -Online -FeatureName "MicrosoftWindowsPowerShellV2Root" -NoRestart -ErrorAction SilentlyContinue | Out-Null
Write-Host "    [OK] PowerShell v2 removed -- WN11-00-000155" -ForegroundColor Green

# Disable LLMNR -- passive NTLMv2 hash capture vector
# DISA CAT II: WN11-CC-000085 | CIS 18.5.4 | NSA/CISA | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient" -Name "EnableMulticast" -Value 0

# Disable NetBIOS over TCP/IP
# DISA CAT II: WN11-CC-000080 | NSA | CCCS ITSP.70.012
Disable-TSGNetBIOS

# Windows Firewall -- all profiles, default-deny inbound
# DISA CAT I: WN11-NX-000010/015/020 | DISA CAT II: WN11-NX-000025/030/035
Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled True
Set-NetFirewallProfile -Profile Domain,Public,Private -DefaultInboundAction Block
Write-Host "    [OK] Firewall enabled, default-deny inbound -- WN11-NX-000010/025" -ForegroundColor Green

# Require SMB packet signing
# DISA CAT II: WN11-SO-000160/165 | CIS 2.3.9.1/2.3.9.2 | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters" -Name "RequireSecuritySignature" -Value 1
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters" -Name "RequireSecuritySignature" -Value 1


# ================================================================================
# WINDOWS DEFENDER
# Source: DISA WN11-00-000270/275
# ================================================================================
Write-TSGSection "WINDOWS DEFENDER" "DISA WN11-00-000270/275"

Set-Service -Name "WinDefend" -StartupType Automatic -ErrorAction SilentlyContinue
Start-Service -Name "WinDefend" -ErrorAction SilentlyContinue
Set-MpPreference -DisableRealtimeMonitoring $false       # WN11-00-000270
Set-MpPreference -EnableNetworkProtection Enabled
Set-MpPreference -EnableControlledFolderAccess Enabled   # Anti-ransomware
Write-Host "    [OK] Defender, network protection, and CFA enabled" -ForegroundColor Green
Write-Host "    [NOTE] If CFA blocks legitimate apps: Add-MpPreference -ControlledFolderAccessAllowedApplications 'App.exe'" -ForegroundColor Yellow


# ================================================================================
# AUDIT POLICY AND LOGGING
# Source: DISA WN11-AU-000010/030/035/045/090/095/500/505/525/530 | WN11-CC-000315/326
# ================================================================================
Write-TSGSection "AUDIT POLICY AND LOGGING" "DISA WN11-AU-000010 through WN11-AU-000560"

# Core audit categories (all verified auditpol subcategory names)
AuditPol /set /subcategory:"Logon"                   /success:enable /failure:enable | Out-Null  # WN11-AU-000030/035
AuditPol /set /subcategory:"Logoff"                  /success:enable                 | Out-Null
AuditPol /set /subcategory:"Account Lockout"         /failure:enable                 | Out-Null
AuditPol /set /subcategory:"Credential Validation"   /success:enable /failure:enable | Out-Null  # WN11-AU-000010/015
AuditPol /set /subcategory:"Process Creation"        /success:enable                 | Out-Null  # WN11-AU-000500
AuditPol /set /subcategory:"Sensitive Privilege Use" /success:enable /failure:enable | Out-Null  # WN11-AU-000090/095
AuditPol /set /subcategory:"Audit Policy Change"     /success:enable /failure:enable | Out-Null  # WN11-AU-000525/530
AuditPol /set /subcategory:"File System"             /success:enable /failure:enable | Out-Null  # WN11-AU-000555/560
AuditPol /set /subcategory:"User Account Management" /success:enable /failure:enable | Out-Null
AuditPol /set /subcategory:"Special Logon"           /success:enable                 | Out-Null
Write-Host "    [OK] Audit policy configured" -ForegroundColor Green

# Process creation command-line capture -- both auditpol AND registry key required
# DISA CAT II: WN11-AU-000500/505
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Audit" -Name "ProcessCreationIncludeCmdLine_Enabled" -Value 1

# Increase event log sizes -- DISA requires minimum 1GB for Security
# DISA CAT II: WN11-AU-000045 | CIS 18.9.26.1 | CCCS ITSP.70.012
wevtutil sl Security    /ms:1073741824 | Out-Null   # 1 GB -- WN11-AU-000045
wevtutil sl Application /ms:268435456  | Out-Null   # 256 MB
wevtutil sl System      /ms:268435456  | Out-Null   # 256 MB
Write-Host "    [OK] Log sizes: Security 1GB, Application/System 256MB" -ForegroundColor Green

# PowerShell Script Block Logging (Event 4104)
# DISA CAT II: WN11-CC-000315 | NSA/CISA June 2022 CSI | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging" -Name "EnableScriptBlockLogging"         -Value 1
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging" -Name "EnableScriptBlockInvocationLogging" -Value 1
wevtutil sl "Microsoft-Windows-PowerShell/Operational" /ms:104857600 | Out-Null

# PowerShell Transcription
# DISA WN11-CC-000326 | NSA/CISA June 2022 CSI | CCCS
$transcriptPath = "C:\Logs\PSTranscripts"
if (-not (Test-Path $transcriptPath)) { New-Item -ItemType Directory -Path $transcriptPath -Force | Out-Null }
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\Transcription" -Name "EnableTranscripting"    -Value 1
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\Transcription" -Name "OutputDirectory"        -Value $transcriptPath -Type String
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\Transcription" -Name "EnableInvocationHeader" -Value 1
Write-Host "    [OK] PS Script Block Logging and Transcription enabled" -ForegroundColor Green


# ================================================================================
# ACCESS CONTROL
# Source: DISA WN11-SO-000245/251 | WN11-CC-000020/030/150 | WN11-00-000031
# ================================================================================
Write-TSGSection "ACCESS CONTROL" "DISA WN11-SO-000245/251 | WN11-CC-000020/030/150 | WN11-00-000031"

# UAC -- Always Notify (maximum level, ConsentPromptBehaviorAdmin = 2)
# DISA CAT I: WN11-SO-000245 | DISA CAT II: WN11-SO-000251
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" -Name "EnableLUA"                 -Value 1
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" -Name "PromptOnSecureDesktop"      -Value 1
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" -Name "ConsentPromptBehaviorAdmin" -Value 2
Write-Host "    [OK] UAC Always Notify -- WN11-SO-000245/251" -ForegroundColor Green

# Disable AutoRun on all drive types (NoDriveTypeAutoRun = 255 = all types)
# DISA CAT II: WN11-CC-000150 | CIS 18.9.8.1 | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer" -Name "NoDriveTypeAutoRun" -Value 255
Set-TSGRegistry -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer" -Name "NoDriveTypeAutoRun" -Value 255

# Disable RDP -- DISA CAT II finding if enabled without operational justification
# DISA CAT II: WN11-CC-000020 | CIS 18.9.59.2 | CCCS ITSP.70.012
# Comment out this block if RDP is operationally required.
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 1
Disable-NetFirewallRule -DisplayGroup "Remote Desktop" -ErrorAction SilentlyContinue
Write-Host "    [OK] RDP disabled -- WN11-CC-000020 (comment out if remote access required)" -ForegroundColor Green

# Require NLA for RDP -- enable even when RDP is disabled (belt and suspenders)
# DISA CAT II: WN11-CC-000030 | CIS 18.9.59.2.1 | CCCS
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "UserAuthentication" -Value 1

# Enable BitLocker -- available on Pro and Enterprise
# DISA CAT II: WN11-00-000031 | NSA | CCCS ITSP.70.012
Write-Host "    Enabling BitLocker on C: ..." -ForegroundColor DarkGray
manage-bde -on C: -RecoveryPassword -SkipHardwareTest
Write-Host "    [NOTE] SAVE THE RECOVERY KEY. Restart required to complete encryption. -- WN11-00-000031" -ForegroundColor Yellow

# Restrict PowerShell execution policy to RemoteSigned
# NSA/CISA June 2022 CSI | CCCS ITSP.70.012
Set-ExecutionPolicy RemoteSigned -Scope LocalMachine -Force

# Block Office macros from internet sources
# DISA STIG | CIS | CCCS ITSP.70.012 | ASD Essential Eight
$officeVersion = "16.0"
foreach ($app in @("Word", "Excel", "PowerPoint", "Outlook", "Access")) {
    Set-TSGRegistry -Path "HKCU:\SOFTWARE\Policies\Microsoft\Office\$officeVersion\$app\Security" -Name "VBAWarnings" -Value 4
}

# Disable Windows Script Host -- blocks .vbs, .js, .wsf execution
# NSA | CCCS ITSP.70.012 | DISA STIG execution vector guidance
# WARNING: verify no VBScript automation is in use before applying
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows Script Host\Settings" -Name "Enabled" -Value 0
Write-Host "    [WARN] WSH disabled -- verify no .vbs/.js automation is in use" -ForegroundColor Yellow

# Enable AppLocker (Enterprise/Education only)
# DISA STIG | CIS L2 | NSA/CISA | CCCS ITSP.70.012
if (Test-TSGEnterprise -ControlName "AppLocker") {
    Set-Service -Name "AppIDSvc" -StartupType Automatic -ErrorAction SilentlyContinue
    Start-Service -Name "AppIDSvc" -ErrorAction SilentlyContinue
    Write-Host "    [OK] AppIDSvc enabled -- configure AppLocker rules via Group Policy" -ForegroundColor Green
}

Write-Host "    [OK] Access control applied" -ForegroundColor Green


# ================================================================================
# TELEMETRY AND PRIVACY
# Source: DISA WN11-CC-000010/206/225 | CIS 18.9.16/44/46
# ================================================================================
Write-TSGSection "TELEMETRY AND PRIVACY" "DISA WN11-CC-000010/206/225"

# Disable DiagTrack
# DISA CAT II: WN11-CC-000206 | CIS 18.9.16.1 | CCCS ITSP.70.012
Stop-Service -Name "DiagTrack" -ErrorAction SilentlyContinue
Set-Service  -Name "DiagTrack" -StartupType Disabled
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection" -Name "AllowTelemetry" -Value 0
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection" -Name "AllowTelemetry" -Value 0

# Disable Activity History
# DISA CAT II: WN11-CC-000225 | CIS 18.9.46.1
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\System" -Name "PublishUserActivities" -Value 0
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\System" -Name "UploadUserActivities"  -Value 0

# Disable Windows Recall
# NSA/CISA | CCCS | PIPEDA
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsAI" -Name "DisableAIDataAnalysis" -Value 1
Set-TSGRegistry -Path "HKCU:\SOFTWARE\Policies\Microsoft\Windows\WindowsAI" -Name "DisableAIDataAnalysis" -Value 1
Disable-WindowsOptionalFeature -Online -FeatureName "Recall" -NoRestart -ErrorAction SilentlyContinue | Out-Null

# Disable Advertising ID
# DISA CAT II: WN11-CC-000010 | CIS 18.9.44.1
Set-TSGRegistry -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\AdvertisingInfo" -Name "Enabled" -Value 0

Write-Host "    [OK] Telemetry, Activity History, Recall, Advertising ID disabled" -ForegroundColor Green


# ================================================================================
# EXPLOIT MITIGATION
# Source: DISA WN11-00-000020/025 | CIS 18.8.21.5 | NSA | CCCS ITSP.70.012
# ================================================================================
Write-TSGSection "EXPLOIT MITIGATION" "DISA WN11-00-000020/025 | CIS 18.8.21.5 | NSA"

# DEP AlwaysOn -- data memory pages non-executable, restart required
# DISA CAT II: WN11-00-000020 | CIS 18.8.21.5 | NSA | CCCS ITSP.70.012
bcdedit /set nx AlwaysOn | Out-Null
Write-Host "    [OK] DEP set to AlwaysOn (restart required) -- WN11-00-000020" -ForegroundColor Green

# ASLR with forced relocation
# CIS | NSA | CCCS ITSP.70.012
Set-ProcessMitigation -System -Enable ASLR,ForceRelocateImages -ErrorAction SilentlyContinue
Write-Host "    [OK] ASLR and forced relocation enabled" -ForegroundColor Green

# SEHOP -- value 0 ENABLES it (counterintuitive, confirmed in DISA STIG WN11-00-000025)
# DISA CAT II: WN11-00-000025 | CIS | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\kernel" -Name "DisableExceptionChainValidation" -Value 0

# Disable hibernation
# NSA | CCCS ITSP.70.012
powercfg -h off
Write-Host "    [OK] Hibernation disabled" -ForegroundColor Green


# ================================================================================
# BLOATWARE REMOVAL
# ================================================================================
Write-TSGSection "BLOATWARE REMOVAL" "Least functionality -- DISA CM controls"

Remove-TSGAppx -PackageName "Microsoft.549981C3F5F10"                -FriendlyName "Cortana"
Remove-TSGAppx -PackageName "Microsoft.Windows.Copilot"              -FriendlyName "Windows Copilot"
Remove-TSGAppx -PackageName "MicrosoftWindows.Client.WebExperience"  -FriendlyName "Windows Widgets"
Remove-TSGAppx -PackageName "Microsoft.BingNews"                     -FriendlyName "Bing News"
Remove-TSGAppx -PackageName "Microsoft.BingWeather"                  -FriendlyName "Bing Weather"
Remove-TSGAppx -PackageName "Microsoft.GamingApp"                    -FriendlyName "Xbox Gaming App"
Remove-TSGAppx -PackageName "Microsoft.XboxApp"                      -FriendlyName "Xbox App"
Remove-TSGAppx -PackageName "Microsoft.XboxGameOverlay"              -FriendlyName "Xbox Game Overlay"
Remove-TSGAppx -PackageName "Microsoft.XboxGamingOverlay"            -FriendlyName "Xbox Gaming Overlay"
Remove-TSGAppx -PackageName "Microsoft.MicrosoftSolitaireCollection" -FriendlyName "Microsoft Solitaire"
Remove-TSGAppx -PackageName "Microsoft.YourPhone"                    -FriendlyName "Phone Link"
Remove-TSGAppx -PackageName "MicrosoftCorporationII.QuickAssist"     -FriendlyName "Quick Assist"
Remove-TSGAppx -PackageName "Microsoft.SkypeApp"                     -FriendlyName "Skype"
Remove-TSGAppx -PackageName "MicrosoftTeams"                         -FriendlyName "Teams Consumer"
Remove-TSGAppx -PackageName "Clipchamp.Clipchamp"                    -FriendlyName "Clipchamp"
Remove-TSGAppx -PackageName "BytedancePte.TikTok"                    -FriendlyName "TikTok"
Remove-TSGAppx -PackageName "Microsoft.WindowsFeedbackHub"           -FriendlyName "Feedback Hub"

Set-TSGRegistry -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "ContentDeliveryAllowed"      -Value 0
Set-TSGRegistry -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "SubscribedContentEnabled"     -Value 0
Set-TSGRegistry -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "SystemPaneSuggestionsEnabled" -Value 0
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\CloudContent" -Name "DisableWindowsConsumerFeatures" -Value 1
Set-TSGRegistry -Path "HKCU:\SOFTWARE\Policies\Microsoft\Windows\CloudContent" -Name "DisableWindowsSpotlightFeatures" -Value 1
Write-Host "    [OK] Consumer apps and Start Menu ads removed" -ForegroundColor Green


# ================================================================================
# FINALIZATION
# ================================================================================
Write-TSGSection "FINALIZATION"

if ($SkippedEntControls.Count -gt 0) {
    Write-Host ""
    Write-Host "  Enterprise-only controls skipped on this Pro SKU:" -ForegroundColor Yellow
    $SkippedEntControls | ForEach-Object { Write-Host "    * $_" -ForegroundColor Yellow }
    Write-Host "  Source: learn.microsoft.com/windows/security/licensing-and-edition-requirements" -ForegroundColor DarkGray
}

Write-Host ""
Write-Host "  DISA STIG baseline applied." -ForegroundColor Cyan
Write-Host "  Log: $LogPath" -ForegroundColor White
Write-Host "  RESTART REQUIRED: DEP, LSA Protection, Credential Guard, BitLocker, SMBv1" -ForegroundColor Yellow
Write-Host "  Hans Study | https://hans.study | contact@hans.study" -ForegroundColor DarkGray

$restart = Read-Host "  Restart now? [y/N]"
if ($restart -match '^[Yy]') {
    Write-Host "  Restarting in 15 seconds. Press Ctrl+C to cancel." -ForegroundColor Yellow
    Start-Sleep -Seconds 15
    Restart-Computer -Force
}

Stop-Transcript | Out-Null
