#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Hardens and tunes a Windows workstation running Genetec Security Center.

.DESCRIPTION
    Applies security hardening and performance tuning specific to Genetec
    Security Center 6.x deployments. Covers VMS workstations running
    Security Desk and Config Tool, as well as dedicated Archiver and
    Directory servers.

    Every decision in this script is documented. Where a standard control
    is intentionally skipped or modified for Genetec compatibility, the
    reason is explained inline.

.NOTES
    ================================================================
    Study Workstation Configurator
    Template: Genetec Security Center

    Generated by Hans Study, CISSP / TSG Labs
    Generated:          2026-05-16
    Config fingerprint: (curated baseline; not configurator output)

    Website:   https://hans.study
    Email:     contact@hans.study
    LinkedIn:  https://linkedin.com/in/hans-study
    Instagram: https://instagram.com/studybyt3s
    X:         https://x.com/studybyt3s
    YouTube:   https://youtube.com/@studybyt3s
    GitHub:    https://github.com/tsglabs

    Target OS:  Windows 10/11 Enterprise or Pro
                Windows Server 2019/2022/2025
    SC Version: Genetec Security Center 6.x
    Version:    2.0

    STANDARDS REFERENCED:
      Genetec Security Center Hardening Guide (publications.genetec.com)
      DISA STIG Windows 11 V2R2              (public.cyber.mil)
      CIS Microsoft Windows 11 Benchmark v3.0 (cisecurity.org)
      NSA/CISA Cybersecurity Information Sheets (media.defense.gov)
      CSE/CCCS ITSP.70.012                   (cyber.gc.ca)

    Source-available. Personal and internal use permitted.
    Redistribution requires written authorization from Hans Study.
    See LICENSE for full terms.
    Test in a lab environment before production deployment.
    Hans Study accepts no liability for unintended consequences.
    ================================================================
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = "Continue"

# ── Logging ───────────────────────────────────────────────────────────────────
# All output is captured to a dated log file in C:\Logs.
# Retain this log as evidence of baseline application.
$LogDate = Get-Date -Format "yyyyMMdd"
$LogPath = "C:\Logs\Genetec-SecurityCenter-Workstation_$LogDate.log"
if (-not (Test-Path "C:\Logs")) {
    New-Item -ItemType Directory -Path "C:\Logs" -Force | Out-Null
}
Start-Transcript -Path $LogPath -Append -IncludeInvocationHeader | Out-Null

# ── Shared functions ──────────────────────────────────────────────────────────
# Dot-source the shared module if it exists alongside this script.
# If not present, the inline fallbacks below handle everything.
# ── HELPER FUNCTIONS ──────────────────────────────────────────────────────────
# These functions are embedded in each script so it runs
# standalone without any module dependency.

# Write-TSGSection: prints a visible section header to the console and transcript
function Write-TSGSection {
    param([string]$Title, [string]$Subtitle = "")
    Write-Host ""
    Write-Host "  ======================================================================" -ForegroundColor DarkGray
    Write-Host "  $Title" -ForegroundColor Yellow
    if ($Subtitle) { Write-Host "  $Subtitle" -ForegroundColor DarkGray }
    Write-Host "  ======================================================================" -ForegroundColor DarkGray
}

# Set-TSGRegistry: idempotent registry write -- creates the key path if missing,
# sets the value, and logs OK or FAIL for every entry. Safe to re-run.
function Set-TSGRegistry {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$Name,
        [Parameter(Mandatory)][object]$Value,
        [ValidateSet("DWord","QWord","String","ExpandString","Binary","MultiString")]
        [string]$Type = "DWord"
    )
    try {
        if (-not (Test-Path $Path)) { New-Item -Path $Path -Force -ErrorAction Stop | Out-Null }
        Set-ItemProperty -Path $Path -Name $Name -Value $Value -Type $Type -Force -ErrorAction Stop
        Write-Host "    [OK] $($Path.Split('\')[-1])\$Name = $Value" -ForegroundColor Green
    } catch {
        Write-Host "    [FAIL] $Name at $Path" -ForegroundColor Red
        Write-Host "           $($_.Exception.Message)" -ForegroundColor DarkGray
    }
}

# Remove-TSGAppx: removes an AppX package for all existing users and prevents
# reinstall for future accounts. Handles missing packages without errors.
function Remove-TSGAppx {
    param([Parameter(Mandatory)][string]$PackageName, [Parameter(Mandatory)][string]$FriendlyName)
    Write-Host "    Removing: $FriendlyName ($PackageName)" -ForegroundColor DarkGray
    try {
        Get-AppxProvisionedPackage -Online -ErrorAction SilentlyContinue |
            Where-Object { $_.DisplayName -like "*$PackageName*" } |
            Remove-AppxProvisionedPackage -Online -ErrorAction SilentlyContinue | Out-Null
        Get-AppxPackage -AllUsers -ErrorAction SilentlyContinue |
            Where-Object { $_.Name -like "*$PackageName*" } |
            Remove-AppxPackage -AllUsers -ErrorAction SilentlyContinue
        Write-Host "    [OK] $FriendlyName removed or already absent" -ForegroundColor Green
    } catch { Write-Host "    [SKIP] $FriendlyName -- $($_.Exception.Message)" -ForegroundColor DarkGray }
}

# Test-TSGEnterprise: checks the OS SKU and gates Enterprise-only controls.
# Credential Guard and AppLocker enforcement require Enterprise or Education.
# Returns $true on Enterprise/Server, $false on Pro with a logged warning.
# Source: learn.microsoft.com/en-us/windows/security/licensing-and-edition-requirements
function Test-TSGEnterprise {
    param([string]$ControlName = "This control")
    $sku = (Get-CimInstance Win32_OperatingSystem -ErrorAction Stop).OperatingSystemSKU
    # Enterprise=4, Enterprise N=27, Enterprise Eval=70, Enterprise N Eval=84,
    # Enterprise G=125, Education=4, Server variants=161-172
    if ($sku -in @(4,27,70,84,125,161,162,163,164,169,170,171,172)) { return $true }
    Write-Host "    [SKIP] $ControlName requires Enterprise or Education license (SKU: $sku)" -ForegroundColor Yellow
    Write-Host "           Source: learn.microsoft.com/windows/security/licensing-and-edition-requirements" -ForegroundColor DarkGray
    $script:SkippedEntControls.Add($ControlName)
    return $false
}

# New-TSGRestorePoint: creates a System Restore point before hardening.
# Can fail on domain machines with Group Policy restrictions -- not fatal.
function New-TSGRestorePoint {
    param([string]$Description = "Hardening Script")
    Write-Host "  Creating system restore point..." -ForegroundColor DarkGray
    try {
        Checkpoint-Computer -Description "$Description $(Get-Date -Format 'yyyy-MM-dd HH:mm')" `
            -RestorePointType "MODIFY_SETTINGS" -ErrorAction Stop
        Write-Host "  [OK] Restore point created" -ForegroundColor Green
    } catch {
        Write-Host "  [WARN] Restore point failed -- continuing ($($_.Exception.Message))" -ForegroundColor Yellow
    }
}

# Disable-TSGNetBIOS: disables NetBIOS over TCP/IP on all IPv4 adapters.
# Uses WMI because there is no native PowerShell cmdlet for this.
# SetTcpipNetbios(2) = disable. Value 1 = enable. Value 0 = use DHCP setting.
function Disable-TSGNetBIOS {
    Write-Host "    Disabling NetBIOS over TCP/IP on all adapters..." -ForegroundColor DarkGray
    try {
        $adapters = Get-WmiObject -Class Win32_NetworkAdapterConfiguration `
            -Filter "IPEnabled = True" -ErrorAction Stop
        $count = 0
        foreach ($adapter in $adapters) {
            $result = $adapter.SetTcpipNetbios(2)
            if ($result.ReturnValue -eq 0) { $count++ }
        }
        Write-Host "    [OK] NetBIOS disabled on $count adapter(s)" -ForegroundColor Green
    } catch { Write-Host "    [FAIL] NetBIOS disable -- $($_.Exception.Message)" -ForegroundColor Red }
}

# ── Header ─────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "  =========================================================" -ForegroundColor Cyan
Write-Host "  Genetec Security Center Hardening + Performance Tuning" -ForegroundColor Cyan
Write-Host "  Hans Study, CISSP | https://hans.study" -ForegroundColor DarkGray
Write-Host "  Log: $LogPath" -ForegroundColor DarkGray
Write-Host "  =========================================================" -ForegroundColor Cyan
Write-Host ""

# ── Edition detection ─────────────────────────────────────────────────────────
# Credential Guard requires Enterprise or Education.
# All other controls in this script work on Pro.
$OsSku = (Get-CimInstance Win32_OperatingSystem).OperatingSystemSKU
$IsEnterprise = $OsSku -in @(4,27,70,84,125,161,162,163,164,169,170,171,172)
Write-Host "  OS SKU: $OsSku | Edition: $(if ($IsEnterprise) { 'Enterprise/Server' } else { 'Pro' })" `
    -ForegroundColor $(if ($IsEnterprise) { "Green" } else { "Yellow" })
Write-Host ""

New-TSGRestorePoint -Description "Genetec Security Center Hardening"


# ════════════════════════════════════════════════════════════════════════════════
# SECTION 1 - CREDENTIAL AND IDENTITY PROTECTION
#
# Genetec Directory service accounts and SQL credentials are high-value targets.
# Credential dumping tools like Mimikatz are the most common way attackers
# escalate after initial access on a VMS workstation.
# ════════════════════════════════════════════════════════════════════════════════
Write-TSGSection "CREDENTIAL AND IDENTITY PROTECTION"

# Disable WDigest credential caching in LSASS
# Source: DISA STIG WN11-CC-000040 | CIS 18.9.29.1 | CCCS ITSP.70.012
#
# WDigest stores credentials in LSASS memory as cleartext. An attacker with
# admin access can dump these using Mimikatz or similar tools. Setting
# UseLogonCredential = 0 prevents this. Works on all editions.
Set-TSGRegistry `
    -Path "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\WDigest" `
    -Name "UseLogonCredential" `
    -Value 0

# Do not store the LAN Manager hash
# Source: DISA STIG WN11-SO-000190 | CIS 2.3.11.6 | CCCS ITSP.70.012
#
# LM hashes are computed using a trivially weak algorithm and can be cracked
# offline in seconds with modern hardware. Setting NoLMHash = 1 prevents the
# LM hash from being stored alongside the stronger NTLM hash.
Set-TSGRegistry `
    -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Lsa" `
    -Name "NoLMHash" `
    -Value 1

# Require NTLMv2, refuse LM and NTLMv1
# Source: DISA STIG WN11-SO-000195 | CIS 2.3.11.7 | CCCS ITSP.70.012
#
# LmCompatibilityLevel = 5: send NTLMv2 response only, refuse all LM and
# NTLMv1 authentication. NTLMv1 is crackable in seconds offline.
# Genetec uses Kerberos on domain and NTLM fallback on workgroup -- NTLMv2 works.
Set-TSGRegistry `
    -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Lsa" `
    -Name "LmCompatibilityLevel" `
    -Value 5

# Enable LSA Protection (RunAsPPL)
# Source: DISA STIG WN11-SO-000100 | CIS 18.3.2 | CCCS ITSP.70.012
#
# Runs LSASS as a Protected Process Light. Blocks most credential-dumping
# tools including Mimikatz in its default configuration. Works on Pro and
# Enterprise. Restart required for this change to take effect.
Set-TSGRegistry `
    -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Lsa" `
    -Name "RunAsPPL" `
    -Value 1
Write-Host "    [NOTE] Restart required for LSA Protection to activate" -ForegroundColor Yellow

# Credential Guard (Enterprise/Education only)
# Source: DISA STIG WN11-00-000095 | NSA/CISA | CCCS ITSP.70.012
#
# Isolates LSASS in a Hyper-V VBS container. Even with admin access, an
# attacker cannot dump credentials from the isolated process. Requires
# UEFI + Secure Boot + TPM 2.0. Skipped automatically on Pro.
if (Test-TSGEnterprise -ControlName "Credential Guard") {
    Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\DeviceGuard" -Name "EnableVirtualizationBasedSecurity" -Value 1
    Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\DeviceGuard" -Name "RequirePlatformSecurityFeatures" -Value 3
    Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\DeviceGuard\Scenarios\CredentialGuard" -Name "Enabled" -Value 1
    Write-Host "    [NOTE] Restart required for Credential Guard to activate" -ForegroundColor Yellow
}


# ════════════════════════════════════════════════════════════════════════════════
# SECTION 2 - NETWORK HARDENING
#
# Genetec communicates over TCP using well-defined ports. It does not rely on
# NetBIOS or LLMNR for any discovery function. Disabling them removes attack
# surface without affecting SC functionality.
# ════════════════════════════════════════════════════════════════════════════════
Write-TSGSection "NETWORK HARDENING"

# Disable SMBv1
# Source: DISA STIG WN11-00-000160/165 | CIS 18.3.3 | NSA | CCCS ITSP.70.012
#
# SMBv1 is the protocol exploited by EternalBlue (WannaCry, NotPetya, BadRabbit).
# No Genetec component requires SMBv1. Disable unconditionally.
# The feature removal and the registry key are belt-and-suspenders -- both needed.
Set-TSGRegistry `
    -Path "HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters" `
    -Name "SMB1" `
    -Value 0
Disable-WindowsOptionalFeature -Online -FeatureName "SMB1Protocol" -NoRestart -ErrorAction SilentlyContinue | Out-Null
Write-Host "    [OK] SMBv1 feature removed and registry key set" -ForegroundColor Green

# Remove PowerShell v2
# Source: DISA STIG WN11-00-000155 | NSA/CISA June 2022 CSI | CCCS ITSP.70.012
#
# PowerShell v2 bypasses all modern security features: AMSI, script block
# logging, constrained language mode. NSA/CISA specifically call out PS v2
# removal in their June 2022 PowerShell security guidance.
# Genetec installer and management scripts use PS 5+.
Disable-WindowsOptionalFeature -Online -FeatureName "MicrosoftWindowsPowerShellV2Root" -NoRestart -ErrorAction SilentlyContinue | Out-Null
Write-Host "    [OK] PowerShell v2 engine removed" -ForegroundColor Green

# Disable LLMNR
# Source: DISA STIG WN11-CC-000085 | CIS 18.5.4 | NSA/CISA | CCCS ITSP.70.012
#
# LLMNR broadcasts unauthenticated name resolution requests to the local subnet.
# Responder and Inveigh capture NTLMv2 hashes from LLMNR queries passively.
# Genetec uses DNS for all name resolution -- LLMNR is pure attack surface.
Set-TSGRegistry `
    -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient" `
    -Name "EnableMulticast" `
    -Value 0

# Disable NetBIOS over TCP/IP
# Source: DISA STIG WN11-CC-000080 | NSA | CCCS ITSP.70.012
#
# NetBIOS exposes machine name, domain, and OS version to the local subnet
# and is exploited for lateral movement. Genetec uses DNS and TCP directly.
Disable-TSGNetBIOS

# Require SMB packet signing
# Source: DISA STIG WN11-SO-000160/165 | CIS 2.3.9.1/2.3.9.2 | CCCS ITSP.70.012
#
# SMB signing ensures packets have not been tampered with in transit.
# Prevents SMB relay attacks where an attacker intercepts authentication
# and uses it to access Genetec archive shares. Both keys are required.
Set-TSGRegistry `
    -Path "HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters" `
    -Name "RequireSecuritySignature" `
    -Value 1
Set-TSGRegistry `
    -Path "HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters" `
    -Name "RequireSecuritySignature" `
    -Value 1

# Enable Windows Firewall on all profiles
# Source: DISA STIG WN11-NX-000010/015/020 | CIS 9.1.1/9.2.1/9.3.1 | CCCS
#
# The host-based firewall is the last line of defense when network controls
# fail. Enable on all profiles. Note: no spaces in the profile list --
# "Domain,Public,Private" is the correct syntax for Set-NetFirewallProfile.
Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled True
Set-NetFirewallProfile -Profile Domain,Public,Private -DefaultInboundAction Block
Write-Host "    [OK] Firewall enabled with default-deny inbound on all profiles" -ForegroundColor Green

# Open required Genetec Security Center firewall ports
# Source: Genetec Security Center Hardening Guide (publications.genetec.com)
#
# These are the default SC communication ports. Adjust if your deployment
# uses non-default port assignments configured in Config Tool.
#
# TCP 5500  - Genetec Directory SDK (client connections)
# TCP 443   - Genetec Web Client and REST API (HTTPS)
# TCP 554   - Genetec Archiver RTSP (live and playback streams)
# TCP 555   - Genetec Archiver (proprietary stream protocol)
# TCP 8888  - Genetec Unit Assistant (camera unit management)
# TCP 4502  - Genetec Patroller (LPR, if used)
Write-Host "    Adding Genetec firewall rules..." -ForegroundColor DarkGray

$genetecRules = @(
    @{ Name = "Genetec-Directory-SDK";   Port = 5500; Description = "Genetec Directory SDK client connections" },
    @{ Name = "Genetec-HTTPS";           Port = 443;  Description = "Genetec Web Client and REST API" },
    @{ Name = "Genetec-Archiver-RTSP";   Port = 554;  Description = "Genetec Archiver RTSP streams" },
    @{ Name = "Genetec-Archiver-Stream"; Port = 555;  Description = "Genetec Archiver proprietary stream protocol" },
    @{ Name = "Genetec-Unit-Assistant";  Port = 8888; Description = "Genetec Unit Assistant camera management" }
)

foreach ($rule in $genetecRules) {
    # Remove existing rule first to avoid duplicates on re-run (idempotent)
    Remove-NetFirewallRule -DisplayName $rule.Name -ErrorAction SilentlyContinue
    New-NetFirewallRule `
        -DisplayName $rule.Name `
        -Direction Inbound `
        -Protocol TCP `
        -LocalPort $rule.Port `
        -Action Allow `
        -Description $rule.Description `
        -ErrorAction SilentlyContinue | Out-Null
    Write-Host "    [OK] Firewall rule: $($rule.Name) (TCP $($rule.Port))" -ForegroundColor Green
}


# ════════════════════════════════════════════════════════════════════════════════
# SECTION 3 - WINDOWS DEFENDER (GENETEC-TUNED)
#
# Windows Defender is compatible with Genetec Security Center. The key is
# proper exclusions. Without them, Defender will scan video archive files
# on every read, causing severe I/O contention on the Archiver.
# ════════════════════════════════════════════════════════════════════════════════
Write-TSGSection "WINDOWS DEFENDER -- GENETEC CONFIGURATION"

# Ensure Defender is running
# Source: DISA STIG WN11-00-000275
Set-Service -Name "WinDefend" -StartupType Automatic -ErrorAction SilentlyContinue
Start-Service -Name "WinDefend" -ErrorAction SilentlyContinue
Write-Host "    [OK] Windows Defender service running" -ForegroundColor Green

# Enable real-time protection
# Source: DISA STIG WN11-00-000270
Set-MpPreference -DisableRealtimeMonitoring $false

# Enable network protection (blocks known malicious IPs/domains at kernel level)
Set-MpPreference -EnableNetworkProtection Enabled

# Disable cloud-delivered protection
#
# Most Genetec deployments run on isolated camera networks with restricted
# outbound internet access. Cloud protection makes outbound connections to
# Microsoft for real-time threat intelligence. Disable it to avoid connectivity
# errors and unexpected latency on air-gapped or restricted networks.
# Remove this block if your network permits outbound HTTPS.
Set-MpPreference -MAPSReporting Disabled
Set-MpPreference -SubmitSamplesConsent NeverSend
Write-Host "    [OK] Cloud protection disabled (isolated network assumption)" -ForegroundColor Green
Write-Host "    [NOTE] Re-enable cloud protection if outbound internet is permitted" -ForegroundColor Yellow

# Do NOT enable Controlled Folder Access on Genetec workstations
#
# Genetec Security Center writes continuously to AppData paths, ProgramData,
# and custom archive directories during normal operation. CFA will block
# these writes until every write path is explicitly whitelisted.
# The result is recording gaps and service failures during initial deployment.
# If you want CFA, run Set-MpPreference -EnableControlledFolderAccess AuditMode
# first, review the event log for 30 days, add all legitimate paths, then
# switch to Enabled.
Write-Host "    [NOTE] Controlled Folder Access intentionally not enabled" -ForegroundColor Yellow
Write-Host "           Use AuditMode first to build the Genetec exclusion list" -ForegroundColor Yellow

# Add Defender exclusions for Genetec-specific file types and paths
#
# These exclusions prevent Defender from scanning video archive content,
# which generates massive I/O with no security benefit. Video files are
# not executable -- scanning them does not catch malware. The tradeoff
# (reduced I/O vs. theoretical scan coverage) is always correct for VMS.

Write-Host "    Adding Genetec-specific Defender exclusions..." -ForegroundColor DarkGray

# Genetec installation directories
# Prevents Defender from scanning SC binaries on every access
$genetecPaths = @(
    "C:\Program Files (x86)\Genetec Security Center",
    "C:\Program Files\Genetec Security Center"
)
foreach ($path in $genetecPaths) {
    Add-MpPreference -ExclusionPath $path -ErrorAction SilentlyContinue
    Write-Host "    [OK] Exclusion path: $path" -ForegroundColor Green
}

# Video archive file extensions
# G64 and G64x are Genetec's proprietary video container formats.
# Scanning them on read causes severe I/O contention on the Archiver,
# especially on systems with large archives (multi-TB).
$genetecExtensions = @("g64", "g64x")
foreach ($ext in $genetecExtensions) {
    Add-MpPreference -ExclusionExtension $ext -ErrorAction SilentlyContinue
    Write-Host "    [OK] Exclusion extension: .$ext" -ForegroundColor Green
}

# SQL database files
# Genetec Directory uses SQL Server (Express or full) for its database.
# Defender scanning open SQL data files causes errors and performance
# degradation. Microsoft recommends excluding these for all SQL deployments.
# Source: support.microsoft.com/en-us/topic/how-to-choose-antivirus-software-to-run-on-computers-that-are-running-sql-server-feda079b-3e24-186b-945a-3051f6f3a584
$sqlExtensions = @("mdf", "ldf", "ndf")
foreach ($ext in $sqlExtensions) {
    Add-MpPreference -ExclusionExtension $ext -ErrorAction SilentlyContinue
    Write-Host "    [OK] Exclusion extension: .$ext (SQL data file)" -ForegroundColor Green
}


# ════════════════════════════════════════════════════════════════════════════════
# SECTION 4 - AUDIT POLICY AND LOGGING
#
# Genetec workstations generate significant event log volume. Increasing log
# sizes is essential -- the default 64MB Security log fills in hours on an
# active Archiver or Directory server.
# ════════════════════════════════════════════════════════════════════════════════
Write-TSGSection "AUDIT POLICY AND LOGGING"

# Logon and logoff events
# Source: DISA STIG WN11-AU-000030/035 | CIS 17.5.1 | CCCS ITSP.70.012
#
# Foundation of any incident investigation. Without these, you cannot
# reconstruct who accessed the Genetec server or when.
AuditPol /set /subcategory:"Logon" /success:enable /failure:enable | Out-Null
AuditPol /set /subcategory:"Logoff" /success:enable | Out-Null
AuditPol /set /subcategory:"Account Lockout" /failure:enable | Out-Null
Write-Host "    [OK] Logon/logoff/lockout auditing enabled" -ForegroundColor Green

# Process creation with command-line arguments
# Source: DISA STIG WN11-AU-000500/505 | NSA/CISA | CCCS ITSP.70.012
#
# Logs every process started including the full command line (Event 4688).
# Critical for detecting malware or unauthorized tools running on a
# Genetec server. Both the auditpol command and the registry key are
# required -- the registry key enables the command-line capture in 4688.
AuditPol /set /subcategory:"Process Creation" /success:enable | Out-Null
Set-TSGRegistry `
    -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Audit" `
    -Name "ProcessCreationIncludeCmdLine_Enabled" `
    -Value 1

# Audit policy changes
# Source: DISA STIG WN11-AU-000525/530 | CIS 17.9.1
#
# Detects if the audit trail itself is tampered with. If an attacker
# modifies audit policy to stop logging, that change is captured here.
AuditPol /set /subcategory:"Audit Policy Change" /success:enable /failure:enable | Out-Null
Write-Host "    [OK] Audit policy configured" -ForegroundColor Green

# Increase event log sizes
# Source: DISA STIG WN11-AU-000045 | CIS 18.9.26.1 | CCCS ITSP.70.012
#
# Genetec Archiver and Directory generate significant event volume.
# The default 64MB Security log fills in hours on an active system.
# Setting it to 1GB provides approximately 30 days of retention on
# a typical Genetec deployment.
wevtutil sl Security    /ms:1073741824 | Out-Null   # 1 GB
wevtutil sl Application /ms:268435456  | Out-Null   # 256 MB (Genetec logs here)
wevtutil sl System      /ms:268435456  | Out-Null   # 256 MB
Write-Host "    [OK] Event log sizes: Security 1GB, Application 256MB, System 256MB" -ForegroundColor Green

# PowerShell Script Block Logging
# Source: DISA STIG WN11-CC-000315 | NSA/CISA June 2022 CSI | CCCS ITSP.70.012
#
# Logs the full content of every PS script block as it executes,
# including deobfuscated code. Captures attacker activity even when
# scripts are obfuscated. Recommended by NSA/CISA as a priority control.
Set-TSGRegistry `
    -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging" `
    -Name "EnableScriptBlockLogging" `
    -Value 1
Set-TSGRegistry `
    -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging" `
    -Name "EnableScriptBlockInvocationLogging" `
    -Value 1
# Increase the PS Operational log to handle the volume of script block events
wevtutil sl "Microsoft-Windows-PowerShell/Operational" /ms:104857600 | Out-Null  # 100 MB
Write-Host "    [OK] PowerShell Script Block Logging enabled (PS log: 100MB)" -ForegroundColor Green


# ════════════════════════════════════════════════════════════════════════════════
# SECTION 5 - ACCESS CONTROL
#
# UAC and autorun controls. RDP is left enabled with NLA enforced because
# Genetec administrators need remote access to Config Tool and Security Desk.
# ════════════════════════════════════════════════════════════════════════════════
Write-TSGSection "ACCESS CONTROL"

# Enable UAC
# Source: DISA STIG WN11-SO-000245 | CIS 2.3.17.1 | CCCS ITSP.70.012
#
# User Account Control should never be disabled. EnableLUA = 1 is the
# registry enforcement.
#
# NOTE: ConsentPromptBehaviorAdmin is set to 1 (notify for app changes, not
# Windows-signed binaries) rather than 2 (always notify). Genetec Config Tool
# occasionally prompts for elevation. Max-level UAC causes double prompts
# that confuse operators. Standard prompt is the right tradeoff here.
Set-TSGRegistry `
    -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" `
    -Name "EnableLUA" `
    -Value 1
Set-TSGRegistry `
    -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" `
    -Name "ConsentPromptBehaviorAdmin" `
    -Value 1
Set-TSGRegistry `
    -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" `
    -Name "PromptOnSecureDesktop" `
    -Value 1

# Disable AutoRun on all drive types
# Source: DISA STIG WN11-CC-000150 | CIS 18.9.8.1 | CCCS ITSP.70.012
#
# Prevents automatic code execution from removable media. Physical access
# to a Genetec server via USB must not allow automatic code execution.
# NoDriveTypeAutoRun = 255 (0xFF) covers all drive types.
Set-TSGRegistry `
    -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer" `
    -Name "NoDriveTypeAutoRun" `
    -Value 255
Set-TSGRegistry `
    -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer" `
    -Name "NoDriveTypeAutoRun" `
    -Value 255

# Require NLA for RDP connections
# Source: DISA STIG WN11-CC-000030 | CIS 18.9.59.2.1 | CCCS
#
# Network Level Authentication requires valid credentials before establishing
# a full RDP session. This blocks pre-authentication exploitation of RDP
# vulnerabilities (BlueKeep, DejaBlue).
#
# RDP is intentionally LEFT ENABLED. Genetec administrators need remote
# access to Config Tool and Security Desk for support and maintenance.
# If RDP is not required in your environment, set fDenyTSConnections = 1.
Set-TSGRegistry `
    -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" `
    -Name "UserAuthentication" `
    -Value 1
Write-Host "    [OK] RDP left enabled -- NLA enforced" -ForegroundColor Green
Write-Host "    [NOTE] To disable RDP: set HKLM:\...\Terminal Server\fDenyTSConnections = 1" -ForegroundColor DarkGray

# Block Office macros from internet sources
# Source: DISA STIG | CIS | CCCS ITSP.70.012
#
# Malicious macros in Office documents are the primary initial access vector
# for phishing campaigns. VBAWarnings = 4 disables all macros without notification.
# Office 2016, 2019, 2021, and 365 all use the 16.0 registry path.
$officeVersion = "16.0"
foreach ($app in @("Word", "Excel", "PowerPoint", "Outlook", "Access")) {
    Set-TSGRegistry `
        -Path "HKCU:\SOFTWARE\Policies\Microsoft\Office\$officeVersion\$app\Security" `
        -Name "VBAWarnings" `
        -Value 4
}
Write-Host "    [OK] Office macros blocked from internet sources" -ForegroundColor Green


# ════════════════════════════════════════════════════════════════════════════════
# SECTION 6 - TELEMETRY AND PRIVACY
#
# Genetec deployments are frequently on isolated camera networks. Telemetry
# services generate outbound connections that can trigger network alerts and
# cause unexpected latency on bandwidth-constrained VMS networks.
# ════════════════════════════════════════════════════════════════════════════════
Write-TSGSection "TELEMETRY AND PRIVACY"

# Disable DiagTrack (Connected User Experiences and Telemetry)
# Source: DISA STIG WN11-CC-000206 | CIS 18.9.16.1 | CCCS ITSP.70.012
#
# DiagTrack is the primary Windows telemetry service. It sends diagnostic
# data to Microsoft on a regular schedule. On isolated VMS networks, this
# generates outbound connections that may fail noisily or trigger alerts.
Stop-Service -Name "DiagTrack" -ErrorAction SilentlyContinue
Set-Service  -Name "DiagTrack" -StartupType Disabled
Set-TSGRegistry `
    -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection" `
    -Name "AllowTelemetry" `
    -Value 0
Set-TSGRegistry `
    -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection" `
    -Name "AllowTelemetry" `
    -Value 0
Write-Host "    [OK] DiagTrack service disabled" -ForegroundColor Green

# Disable Windows Recall
# Source: NSA/CISA | CCCS | PIPEDA (Canadian privacy law)
#
# Recall takes continuous screenshots of the screen for AI indexing.
# On a Genetec workstation showing live camera feeds, Recall would index
# surveillance footage -- a significant privacy and compliance concern
# under most municipal camera bylaws and Canadian PIPEDA.
Set-TSGRegistry `
    -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsAI" `
    -Name "DisableAIDataAnalysis" `
    -Value 1
Set-TSGRegistry `
    -Path "HKCU:\SOFTWARE\Policies\Microsoft\Windows\WindowsAI" `
    -Name "DisableAIDataAnalysis" `
    -Value 1
Disable-WindowsOptionalFeature -Online -FeatureName "Recall" -NoRestart -ErrorAction SilentlyContinue | Out-Null
Write-Host "    [OK] Windows Recall disabled" -ForegroundColor Green

# Disable Activity History
# Source: DISA STIG WN11-CC-000225 | CIS 18.9.46.1
Set-TSGRegistry `
    -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\System" `
    -Name "PublishUserActivities" `
    -Value 0
Set-TSGRegistry `
    -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\System" `
    -Name "UploadUserActivities" `
    -Value 0


# ════════════════════════════════════════════════════════════════════════════════
# SECTION 7 - PERFORMANCE TUNING (GENETEC-SPECIFIC)
#
# These settings prevent the OS from interfering with Genetec's recording,
# decoding, and database operations. Each setting is explained in terms of
# its specific impact on SC performance.
# ════════════════════════════════════════════════════════════════════════════════
Write-TSGSection "PERFORMANCE TUNING -- GENETEC"

# Set High Performance power plan
#
# The High Performance plan prevents CPU P-state transitions that throttle
# processor speed. On Genetec Archiver servers, throttling causes dropped
# frames during peak recording load. On Security Desk workstations, it
# causes video decode stuttering at high camera counts.
#
# GUID 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c is the built-in High Performance
# plan present on all Windows versions. The script creates it if it has been
# removed by OEM imaging tools.
$highPerfGuid = "8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c"
powercfg -setactive $highPerfGuid 2>$null
if ($LASTEXITCODE -ne 0) {
    # Plan was removed -- duplicate and activate it
    powercfg -duplicatescheme $highPerfGuid | Out-Null
    powercfg -setactive $highPerfGuid | Out-Null
}
Write-Host "    [OK] Power plan: High Performance" -ForegroundColor Green

# Disable hibernation and remove hiberfil.sys
#
# Recording servers must never hibernate. If the Archiver hibernates, it
# loses all active recording connections. Cameras will attempt to reconnect
# but the gap in recording cannot be recovered. hiberfil.sys also consumes
# significant disk space on systems with large RAM (16-64GB+) -- disk space
# that should be available for video archive storage.
powercfg -h off
Write-Host "    [OK] Hibernation disabled, hiberfil.sys removed" -ForegroundColor Green

# Disable Windows Search Indexing
#
# Genetec Security Center has its own media index for the video archive.
# The Windows Search Indexer (WSearch service) constantly reads files to
# build its index. On a system with a large Genetec archive, this creates
# competing I/O that degrades Archiver throughput. SC does not use Windows
# Search -- disabling it provides no functional loss.
Stop-Service -Name "WSearch" -ErrorAction SilentlyContinue
Set-Service  -Name "WSearch" -StartupType Disabled
Write-Host "    [OK] Windows Search Indexing disabled" -ForegroundColor Green

# Disable SysMain (Superfetch)
#
# SysMain pre-loads frequently used applications into RAM. On Genetec
# Archiver and Directory servers that run 24/7 with a fixed workload,
# SysMain provides no benefit and consumes RAM that should be available
# for the Archiver's video buffer and SQL Server's buffer pool.
Stop-Service -Name "SysMain" -ErrorAction SilentlyContinue
Set-Service  -Name "SysMain" -StartupType Disabled
Write-Host "    [OK] SysMain (Superfetch) disabled" -ForegroundColor Green

# Optimize visual effects for performance
#
# Security Desk operators do not need animated menus. Disabling visual effects
# frees GPU resources for video decoding. On systems with many simultaneous
# camera streams, this is a meaningful improvement.
Set-TSGRegistry `
    -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects" `
    -Name "VisualFXSetting" `
    -Value 2


# ════════════════════════════════════════════════════════════════════════════════
# SECTION 8 - EXPLOIT MITIGATION
# ════════════════════════════════════════════════════════════════════════════════
Write-TSGSection "EXPLOIT MITIGATION"

# Data Execution Prevention
# Source: DISA STIG WN11-00-000020 | CIS 18.8.21.5 | NSA | CCCS ITSP.70.012
#
# DEP marks data memory pages as non-executable. Blocks shellcode injected
# into heap or stack from executing. AlwaysOn applies to all processes,
# including Genetec SC binaries. Restart required.
bcdedit /set nx AlwaysOn | Out-Null
Write-Host "    [OK] DEP set to AlwaysOn (restart required)" -ForegroundColor Green

# SEHOP (Structured Exception Handler Overwrite Protection)
# Source: DISA STIG WN11-00-000025 | CIS | CCCS ITSP.70.012
#
# Validates the exception handler chain before dispatching. Blocks SEH
# overwrite exploits. Note the counterintuitive registry value name:
# DisableExceptionChainValidation = 0 ENABLES SEHOP.
# This is confirmed correct in DISA STIG WN11-00-000025.
Set-TSGRegistry `
    -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\kernel" `
    -Name "DisableExceptionChainValidation" `
    -Value 0


# ════════════════════════════════════════════════════════════════════════════════
# SECTION 9 - BLOATWARE REMOVAL
#
# Remove consumer applications that have no place on a VMS workstation.
# These generate background network connections and consume resources.
# ════════════════════════════════════════════════════════════════════════════════
Write-TSGSection "BLOATWARE REMOVAL"

# Consumer apps removed from Genetec workstations
# Each of these generates outbound network connections or consumes CPU/RAM
# in the background -- resources that should go to Genetec SC.
Remove-TSGAppx -PackageName "Microsoft.549981C3F5F10"               -FriendlyName "Cortana"
Remove-TSGAppx -PackageName "Microsoft.Windows.Copilot"             -FriendlyName "Windows Copilot"
Remove-TSGAppx -PackageName "MicrosoftWindows.Client.WebExperience" -FriendlyName "Windows Widgets"
Remove-TSGAppx -PackageName "Microsoft.BingNews"                    -FriendlyName "Bing News"
Remove-TSGAppx -PackageName "Microsoft.BingWeather"                 -FriendlyName "Bing Weather"
Remove-TSGAppx -PackageName "Microsoft.GamingApp"                   -FriendlyName "Xbox Gaming App"
Remove-TSGAppx -PackageName "Microsoft.XboxApp"                     -FriendlyName "Xbox App"
Remove-TSGAppx -PackageName "Microsoft.XboxGameOverlay"             -FriendlyName "Xbox Game Overlay"
Remove-TSGAppx -PackageName "Microsoft.XboxGamingOverlay"           -FriendlyName "Xbox Gaming Overlay"
Remove-TSGAppx -PackageName "Microsoft.MicrosoftSolitaireCollection" -FriendlyName "Microsoft Solitaire"
Remove-TSGAppx -PackageName "Microsoft.YourPhone"                   -FriendlyName "Phone Link"
Remove-TSGAppx -PackageName "Clipchamp.Clipchamp"                   -FriendlyName "Clipchamp Video Editor"
Remove-TSGAppx -PackageName "BytedancePte.TikTok"                   -FriendlyName "TikTok"

# Disable Start Menu ads and cloud content suggestions
# These generate background connections and interfere with operator focus.
Set-TSGRegistry -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "ContentDeliveryAllowed" -Value 0
Set-TSGRegistry -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "SubscribedContentEnabled" -Value 0
Set-TSGRegistry -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "SystemPaneSuggestionsEnabled" -Value 0
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\CloudContent" -Name "DisableWindowsConsumerFeatures" -Value 1

# Disable Windows Spotlight (makes outbound connections to fetch background images)
Set-TSGRegistry -Path "HKCU:\SOFTWARE\Policies\Microsoft\Windows\CloudContent" -Name "DisableWindowsSpotlightFeatures" -Value 1


# ════════════════════════════════════════════════════════════════════════════════
# FINALIZATION
# ════════════════════════════════════════════════════════════════════════════════
Write-TSGSection "FINALIZATION"

Write-Host ""
Write-Host "  Genetec Security Center hardening complete." -ForegroundColor Cyan
Write-Host "  Log saved to: $LogPath" -ForegroundColor White
Write-Host ""
Write-Host "  RESTART REQUIRED for:" -ForegroundColor Yellow
Write-Host "    DEP (bcdedit), LSA Protection (RunAsPPL), Credential Guard" -ForegroundColor Yellow
Write-Host ""
Write-Host "  POST-RESTART CHECKLIST:" -ForegroundColor White
Write-Host "    1. Verify Genetec services start: Security Center, Archiver, Directory" -ForegroundColor DarkGray
Write-Host "    2. Open Config Tool and verify cameras are recording" -ForegroundColor DarkGray
Write-Host "    3. Open Security Desk and verify live video on affected cameras" -ForegroundColor DarkGray
Write-Host "    4. Review C:\Logs\ for any [FAIL] entries and address them" -ForegroundColor DarkGray
Write-Host "    5. If Defender blocks SC processes, add exceptions:" -ForegroundColor DarkGray
Write-Host "       Add-MpPreference -ExclusionProcess 'GenetecServer.exe'" -ForegroundColor DarkGray
Write-Host "       Add-MpPreference -ExclusionProcess 'GenetecVideoArchive.exe'" -ForegroundColor DarkGray
Write-Host ""
Write-Host "  Hans Study | https://hans.study | contact@hans.study" -ForegroundColor DarkGray
Write-Host "  Hans Study, CISSP | LinkedIn: https://linkedin.com/in/hans-study | @studybyt3s | @tsglabs" -ForegroundColor DarkGray

$restart = Read-Host "  Restart now to apply all changes? [y/N]"
if ($restart -match '^[Yy]') {
    Write-Host "  Restarting in 15 seconds. Press Ctrl+C to cancel." -ForegroundColor Yellow
    Start-Sleep -Seconds 15
    Restart-Computer -Force
}

Stop-Transcript | Out-Null
