#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Applies maximum lockdown hardening for a kiosk, thin client, or guard terminal.

.DESCRIPTION
    Designed for single-purpose machines: guard terminals, reception kiosks, lobby
    access control consoles, operator display stations. Everything that can be
    disabled is disabled. Assumes the machine runs one application and operators
    should not be able to deviate from that.

    Key decisions:
      RDP is DISABLED. No remote administration on a kiosk -- physical access only.
      NetBIOS, LLMNR, and IPv6 are all DISABLED. Kiosks do not need them.
      UAC is set to Always Notify. Any elevation on a kiosk should be conspicuous.
      WSH is DISABLED. No script execution of any kind on a locked-down machine.
      High Performance power plan is ON. Kiosks run 24/7, throttling is wrong.
      Hibernation is DISABLED. Kiosks must never sleep or hibernate.
      All consumer apps are removed. Clean OS only.
      BitLocker is enabled. Physical access must not yield data access.

.NOTES
    ================================================================
    Study Workstation Configurator
    Template: Kiosk / Thin Client / Guard Terminal

    Generated by Hans Study, CISSP / TSG Labs
    Generated:          2026-05-16
    Config fingerprint: (curated baseline; not configurator output)

    Website:   https://hans.study
    Email:     contact@hans.study
    LinkedIn:  https://linkedin.com/in/hans-study
    Instagram: https://instagram.com/studybyt3s
    X:         https://x.com/studybyt3s
    YouTube:   https://youtube.com/@studybyt3s
    GitHub:    https://github.com/tsglabs

    Target OS:  Windows 10/11 Pro or Enterprise
    Version:    2.0

    STANDARDS REFERENCED:
      DISA STIG Windows 11 V2R2 / Windows 10 V2R7 (public.cyber.mil)
      CIS Microsoft Windows 11 Benchmark Level 2   (cisecurity.org)
      NSA/CISA Cybersecurity Information Sheets    (media.defense.gov)
      CSE/CCCS ITSP.70.012                         (cyber.gc.ca)

    Source-available. Personal and internal use permitted.
    Redistribution requires written authorization from Hans Study.
    See LICENSE for full terms.
    Test against your kiosk application before production deployment.
    Hans Study accepts no liability for unintended consequences.
    ================================================================
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = "Continue"
$SkippedEntControls = [System.Collections.Generic.List[string]]::new()

$LogDate = Get-Date -Format "yyyyMMdd"
$LogPath = "C:\Logs\Kiosk-ThinClient-Lockdown_$LogDate.log"
if (-not (Test-Path "C:\Logs")) { New-Item -ItemType Directory -Path "C:\Logs" -Force | Out-Null }
Start-Transcript -Path $LogPath -Append -IncludeInvocationHeader | Out-Null

$sharedModule = Join-Path $PSScriptRoot "TSG-Shared.psm1"
if (Test-Path $sharedModule) { . $sharedModule }
else {
    function Write-TSGSection { param([string]$Title, [string]$Subtitle = "")
        Write-Host ""; Write-Host "  == $Title" -ForegroundColor Yellow
        if ($Subtitle) { Write-Host "     $Subtitle" -ForegroundColor DarkGray }
    }
    function Set-TSGRegistry { param([string]$Path, [string]$Name, [object]$Value, [string]$Type = "DWord")
        try {
            if (-not (Test-Path $Path)) { New-Item -Path $Path -Force | Out-Null }
            Set-ItemProperty -Path $Path -Name $Name -Value $Value -Type $Type -Force -ErrorAction Stop
            Write-Host "    [OK] $($Path.Split('\')[-1])\$Name = $Value" -ForegroundColor Green
        } catch { Write-Host "    [FAIL] $Name -- $($_.Exception.Message)" -ForegroundColor Red }
    }
    function Remove-TSGAppx { param([string]$PackageName, [string]$FriendlyName)
        try {
            Get-AppxProvisionedPackage -Online -ErrorAction SilentlyContinue |
                Where-Object { $_.DisplayName -like "*$PackageName*" } |
                Remove-AppxProvisionedPackage -Online -ErrorAction SilentlyContinue | Out-Null
            Get-AppxPackage -AllUsers -ErrorAction SilentlyContinue |
                Where-Object { $_.Name -like "*$PackageName*" } |
                Remove-AppxPackage -AllUsers -ErrorAction SilentlyContinue
            Write-Host "    [OK] $FriendlyName removed or already absent" -ForegroundColor Green
        } catch { Write-Host "    [SKIP] $FriendlyName" -ForegroundColor DarkGray }
    }
    function Test-TSGEnterprise { param([string]$ControlName = "This control")
        $sku = (Get-CimInstance Win32_OperatingSystem).OperatingSystemSKU
        if ($sku -in @(4,27,70,84,125,161,162,163,164,169,170,171,172)) { return $true }
        Write-Host "    [SKIP] $ControlName requires Enterprise license (SKU: $sku)" -ForegroundColor Yellow
        $script:SkippedEntControls.Add($ControlName); return $false
    }
    function New-TSGRestorePoint { param([string]$Description = "Hardening")
        try { Checkpoint-Computer -Description "$Description $(Get-Date -Format 'yyyy-MM-dd')" -RestorePointType "MODIFY_SETTINGS" -ErrorAction Stop
              Write-Host "  [OK] Restore point created" -ForegroundColor Green }
        catch { Write-Host "  [WARN] Restore point failed -- continuing" -ForegroundColor Yellow }
    }
    function Disable-TSGNetBIOS {
        try {
            $adapters = Get-WmiObject -Class Win32_NetworkAdapterConfiguration -Filter "IPEnabled = True"
            foreach ($a in $adapters) { $a.SetTcpipNetbios(2) | Out-Null }
            Write-Host "    [OK] NetBIOS over TCP/IP disabled on all adapters" -ForegroundColor Green
        } catch { Write-Host "    [FAIL] $($_.Exception.Message)" -ForegroundColor Red }
    }
}

Write-Host ""
Write-Host "  =========================================================" -ForegroundColor Cyan
Write-Host "  Kiosk / Thin Client / Guard Terminal Lockdown" -ForegroundColor Cyan
Write-Host "  Maximum restriction for single-purpose Windows deployments" -ForegroundColor White
Write-Host "  Hans Study, CISSP | https://hans.study" -ForegroundColor DarkGray
Write-Host "  Log: $LogPath" -ForegroundColor DarkGray
Write-Host "  =========================================================" -ForegroundColor Cyan
Write-Host ""

$OsSku = (Get-CimInstance Win32_OperatingSystem).OperatingSystemSKU
$IsEnterprise = $OsSku -in @(4,27,70,84,125,161,162,163,164,169,170,171,172)
Write-Host "  OS SKU: $OsSku | Edition: $(if ($IsEnterprise) { 'Enterprise/Server' } else { 'Pro' })" `
    -ForegroundColor $(if ($IsEnterprise) { "Green" } else { "Yellow" })
Write-Host ""

New-TSGRestorePoint -Description "Kiosk / Thin Client Lockdown"


# ================================================================================
# CREDENTIAL AND IDENTITY PROTECTION
# Source: DISA WN11-CC-000040 | WN11-SO-000100/190/195 | WN11-00-000095
# ================================================================================
Write-TSGSection "CREDENTIAL AND IDENTITY PROTECTION" "DISA WN11-CC-000040 | WN11-SO-000100/190/195"

Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\WDigest" -Name "UseLogonCredential" -Value 0  # WN11-CC-000040
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Lsa" -Name "NoLMHash"           -Value 1                         # WN11-SO-000190
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Lsa" -Name "LmCompatibilityLevel" -Value 5                       # WN11-SO-000195
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Lsa" -Name "RunAsPPL"           -Value 1                         # WN11-SO-000100
Write-Host "    [NOTE] Restart required for LSA Protection" -ForegroundColor Yellow

if (Test-TSGEnterprise -ControlName "Credential Guard (WN11-00-000095)") {
    Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\DeviceGuard" -Name "EnableVirtualizationBasedSecurity" -Value 1
    Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\DeviceGuard" -Name "RequirePlatformSecurityFeatures"   -Value 3
    Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\DeviceGuard\Scenarios\CredentialGuard" -Name "Enabled" -Value 1
    Write-Host "    [NOTE] Restart required for Credential Guard" -ForegroundColor Yellow
}


# ================================================================================
# NETWORK HARDENING -- MAXIMUM RESTRICTION
# Source: DISA WN11-00-000155/160/165 | WN11-CC-000080/085 | WN11-NX | WN11-SO-000160/165
# ================================================================================
Write-TSGSection "NETWORK HARDENING -- MAXIMUM RESTRICTION" "DISA WN11-00-000155/160/165 | WN11-CC-000080/085"

Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters" -Name "SMB1" -Value 0                  # WN11-00-000165
Disable-WindowsOptionalFeature -Online -FeatureName "SMB1Protocol" -NoRestart -ErrorAction SilentlyContinue | Out-Null
Write-Host "    [OK] SMBv1 disabled" -ForegroundColor Green

Disable-WindowsOptionalFeature -Online -FeatureName "MicrosoftWindowsPowerShellV2Root" -NoRestart -ErrorAction SilentlyContinue | Out-Null
Write-Host "    [OK] PowerShell v2 removed" -ForegroundColor Green

Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient" -Name "EnableMulticast" -Value 0                 # WN11-CC-000085

Disable-TSGNetBIOS  # WN11-CC-000080

# Disable IPv6 -- kiosk machines do not need it, removes attack surface
# Source: NSA IPv6 guidance | CCCS ITSP.70.012
# DisabledComponents = 0xFF disables all IPv6 components including Teredo and ISATAP
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters" -Name "DisabledComponents" -Value 255
Write-Host "    [OK] IPv6 disabled (restart required)" -ForegroundColor Green

Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled True
Set-NetFirewallProfile -Profile Domain,Public,Private -DefaultInboundAction Block
Write-Host "    [OK] Firewall enabled, default-deny inbound" -ForegroundColor Green

Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters"    -Name "RequireSecuritySignature" -Value 1  # WN11-SO-000160
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters" -Name "RequireSecuritySignature" -Value 1  # WN11-SO-000165


# ================================================================================
# WINDOWS DEFENDER
# Source: DISA WN11-00-000270/275
# ================================================================================
Write-TSGSection "WINDOWS DEFENDER" "DISA WN11-00-000270/275"

Set-Service -Name "WinDefend" -StartupType Automatic -ErrorAction SilentlyContinue
Start-Service -Name "WinDefend" -ErrorAction SilentlyContinue
Set-MpPreference -DisableRealtimeMonitoring $false
Set-MpPreference -EnableNetworkProtection Enabled

# Enable Controlled Folder Access on kiosk machines
# Kiosk applications typically write to one or two known paths.
# CFA blocks ransomware from encrypting kiosk content.
# If CFA blocks your kiosk app, add an exclusion:
#   Add-MpPreference -ControlledFolderAccessAllowedApplications "C:\KioskApp\App.exe"
Set-MpPreference -EnableControlledFolderAccess Enabled
Write-Host "    [OK] Defender with CFA enabled (anti-ransomware)" -ForegroundColor Green
Write-Host "    [NOTE] If CFA blocks the kiosk app: Add-MpPreference -ControlledFolderAccessAllowedApplications 'App.exe'" -ForegroundColor Yellow


# ================================================================================
# AUDIT POLICY AND LOGGING
# Source: DISA WN11-AU | NSA/CISA June 2022 CSI | CCCS ITSP.70.012
# ================================================================================
Write-TSGSection "AUDIT POLICY AND LOGGING" "DISA WN11-AU-000010 through WN11-AU-000560"

AuditPol /set /subcategory:"Logon"                   /success:enable /failure:enable | Out-Null
AuditPol /set /subcategory:"Logoff"                  /success:enable                 | Out-Null
AuditPol /set /subcategory:"Account Lockout"         /failure:enable                 | Out-Null
AuditPol /set /subcategory:"Credential Validation"   /success:enable /failure:enable | Out-Null
AuditPol /set /subcategory:"Process Creation"        /success:enable                 | Out-Null
AuditPol /set /subcategory:"Audit Policy Change"     /success:enable /failure:enable | Out-Null
AuditPol /set /subcategory:"User Account Management" /success:enable /failure:enable | Out-Null
Write-Host "    [OK] Audit policy configured" -ForegroundColor Green

Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Audit" -Name "ProcessCreationIncludeCmdLine_Enabled" -Value 1

wevtutil sl Security    /ms:1073741824 | Out-Null   # 1 GB
wevtutil sl Application /ms:268435456  | Out-Null   # 256 MB
wevtutil sl System      /ms:268435456  | Out-Null   # 256 MB
Write-Host "    [OK] Log sizes: Security 1GB" -ForegroundColor Green

Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging" -Name "EnableScriptBlockLogging"         -Value 1
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging" -Name "EnableScriptBlockInvocationLogging" -Value 1
wevtutil sl "Microsoft-Windows-PowerShell/Operational" /ms:104857600 | Out-Null
Write-Host "    [OK] PS Script Block Logging enabled" -ForegroundColor Green


# ================================================================================
# ACCESS CONTROL -- MAXIMUM RESTRICTION
# Source: DISA WN11-SO-000245/251 | WN11-CC-000020/030/150 | WN11-00-000031
# ================================================================================
Write-TSGSection "ACCESS CONTROL -- MAXIMUM RESTRICTION" "DISA WN11-SO-000245/251 | WN11-CC-000020/030/150"

# UAC -- Always Notify (ConsentPromptBehaviorAdmin = 2)
# Any elevation attempt on a kiosk should be conspicuous and require admin interaction
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" -Name "EnableLUA"                 -Value 1
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" -Name "PromptOnSecureDesktop"      -Value 1
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" -Name "ConsentPromptBehaviorAdmin" -Value 2

# Standard user elevation blocked (ConsentPromptBehaviorUser = 0 = auto-deny)
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" -Name "ConsentPromptBehaviorUser"  -Value 0

# Disable AutoRun on all drive types
# Source: DISA WN11-CC-000150 | CIS 18.9.8.1 | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer" -Name "NoDriveTypeAutoRun" -Value 255
Set-TSGRegistry -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer" -Name "NoDriveTypeAutoRun" -Value 255

# Disable RDP -- no remote administration on a kiosk, physical access only
# Source: DISA WN11-CC-000020 | CIS 18.9.59.2 | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 1
Disable-NetFirewallRule -DisplayGroup "Remote Desktop" -ErrorAction SilentlyContinue
Write-Host "    [OK] RDP disabled" -ForegroundColor Green

# NLA still enforced even with RDP disabled -- belt and suspenders
# Source: DISA WN11-CC-000030 | CIS 18.9.59.2.1 | CCCS
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "UserAuthentication" -Value 1

# Enable BitLocker -- physical access to a kiosk must not yield data access
# Available on Pro and Enterprise. Requires TPM.
# Source: DISA WN11-00-000031 | NSA | CCCS ITSP.70.012
Write-Host "    Enabling BitLocker on C: ..." -ForegroundColor DarkGray
manage-bde -on C: -RecoveryPassword -SkipHardwareTest
Write-Host "    [NOTE] SAVE THE RECOVERY KEY. Restart required to complete encryption." -ForegroundColor Yellow

# Restrict PowerShell execution policy to RemoteSigned
Set-ExecutionPolicy RemoteSigned -Scope LocalMachine -Force

# Block Office macros from internet sources
$officeVersion = "16.0"
foreach ($app in @("Word", "Excel", "PowerPoint", "Outlook", "Access")) {
    Set-TSGRegistry -Path "HKCU:\SOFTWARE\Policies\Microsoft\Office\$officeVersion\$app\Security" -Name "VBAWarnings" -Value 4
}

# Disable Windows Script Host -- no script execution on a kiosk
# Source: NSA | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows Script Host\Settings" -Name "Enabled" -Value 0
Write-Host "    [WARN] WSH disabled -- no .vbs or .js execution permitted" -ForegroundColor Yellow

# AppLocker -- Enterprise/Education only, starts the service
# Rule configuration via Group Policy is required separately
# Source: DISA STIG | CIS L2 | NSA/CISA | CCCS ITSP.70.012
if (Test-TSGEnterprise -ControlName "AppLocker") {
    Set-Service -Name "AppIDSvc" -StartupType Automatic -ErrorAction SilentlyContinue
    Start-Service -Name "AppIDSvc" -ErrorAction SilentlyContinue
    Write-Host "    [OK] AppIDSvc enabled -- configure AppLocker rules via Group Policy" -ForegroundColor Green
}

Write-Host "    [OK] Access control applied" -ForegroundColor Green


# ================================================================================
# TELEMETRY AND PRIVACY
# Source: DISA WN11-CC-000010/206/225 | NSA/CISA | CCCS | PIPEDA
# ================================================================================
Write-TSGSection "TELEMETRY AND PRIVACY" "DISA WN11-CC-000010/206/225"

Stop-Service -Name "DiagTrack" -ErrorAction SilentlyContinue
Set-Service  -Name "DiagTrack" -StartupType Disabled
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection" -Name "AllowTelemetry" -Value 0
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection" -Name "AllowTelemetry" -Value 0
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\System" -Name "PublishUserActivities" -Value 0
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\System" -Name "UploadUserActivities"  -Value 0
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsAI" -Name "DisableAIDataAnalysis" -Value 1
Set-TSGRegistry -Path "HKCU:\SOFTWARE\Policies\Microsoft\Windows\WindowsAI" -Name "DisableAIDataAnalysis" -Value 1
Disable-WindowsOptionalFeature -Online -FeatureName "Recall" -NoRestart -ErrorAction SilentlyContinue | Out-Null
Set-TSGRegistry -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\AdvertisingInfo" -Name "Enabled" -Value 0
Write-Host "    [OK] Telemetry, Recall, Advertising ID disabled" -ForegroundColor Green


# ================================================================================
# PERFORMANCE TUNING -- KIOSK RUNS 24/7
# Kiosks need consistent performance, not power management tradeoffs.
# ================================================================================
Write-TSGSection "PERFORMANCE TUNING -- 24/7 OPERATION" "best practice"

# High Performance power plan -- prevents CPU P-state throttling
# GUID 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c is the built-in High Performance plan
$highPerfGuid = "8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c"
powercfg -setactive $highPerfGuid 2>$null
if ($LASTEXITCODE -ne 0) {
    # Plan may have been removed by OEM imaging -- duplicate and activate it
    powercfg -duplicatescheme $highPerfGuid | Out-Null
    powercfg -setactive $highPerfGuid | Out-Null
}
Write-Host "    [OK] Power plan: High Performance" -ForegroundColor Green

# Disable hibernation -- kiosks must never hibernate
# Hibernate causes a cold-start reconnect cycle that disrupts kiosk application state
powercfg -h off
Write-Host "    [OK] Hibernation disabled" -ForegroundColor Green

# Disable SysMain (Superfetch) -- no benefit on a fixed-workload 24/7 machine
Stop-Service -Name "SysMain" -ErrorAction SilentlyContinue
Set-Service  -Name "SysMain" -StartupType Disabled
Write-Host "    [OK] SysMain (Superfetch) disabled" -ForegroundColor Green

# Disable Windows Search Indexing -- kiosks do not use Windows Search
Stop-Service -Name "WSearch" -ErrorAction SilentlyContinue
Set-Service  -Name "WSearch" -StartupType Disabled
Write-Host "    [OK] Windows Search Indexing disabled" -ForegroundColor Green

# Performance visual effects -- appearance is irrelevant on a kiosk
Set-TSGRegistry -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects" -Name "VisualFXSetting" -Value 2
Write-Host "    [OK] Visual effects set to performance mode" -ForegroundColor Green


# ================================================================================
# EXPLOIT MITIGATION
# Source: DISA WN11-00-000020/025 | CIS 18.8.21.5 | NSA | CCCS ITSP.70.012
# ================================================================================
Write-TSGSection "EXPLOIT MITIGATION" "DISA WN11-00-000020/025 | CIS 18.8.21.5"

bcdedit /set nx AlwaysOn | Out-Null
Write-Host "    [OK] DEP set to AlwaysOn (restart required)" -ForegroundColor Green

Set-ProcessMitigation -System -Enable ASLR,ForceRelocateImages -ErrorAction SilentlyContinue
Write-Host "    [OK] ASLR and forced relocation enabled" -ForegroundColor Green

# Value 0 ENABLES SEHOP (counterintuitive registry name, confirmed in DISA WN11-00-000025)
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\kernel" -Name "DisableExceptionChainValidation" -Value 0


# ================================================================================
# BLOATWARE REMOVAL -- COMPLETE
# ================================================================================
Write-TSGSection "BLOATWARE REMOVAL -- COMPLETE" "Least functionality | DISA CM controls"

Remove-TSGAppx -PackageName "Microsoft.549981C3F5F10"                -FriendlyName "Cortana"
Remove-TSGAppx -PackageName "Microsoft.Windows.Copilot"              -FriendlyName "Windows Copilot"
Remove-TSGAppx -PackageName "MicrosoftWindows.Client.WebExperience"  -FriendlyName "Windows Widgets"
Remove-TSGAppx -PackageName "Microsoft.BingNews"                     -FriendlyName "Bing News"
Remove-TSGAppx -PackageName "Microsoft.BingWeather"                  -FriendlyName "Bing Weather"
Remove-TSGAppx -PackageName "Microsoft.GamingApp"                    -FriendlyName "Xbox Gaming App"
Remove-TSGAppx -PackageName "Microsoft.XboxApp"                      -FriendlyName "Xbox App"
Remove-TSGAppx -PackageName "Microsoft.XboxGameOverlay"              -FriendlyName "Xbox Game Overlay"
Remove-TSGAppx -PackageName "Microsoft.XboxGamingOverlay"            -FriendlyName "Xbox Gaming Overlay"
Remove-TSGAppx -PackageName "Microsoft.Xbox.TCUI"                    -FriendlyName "Xbox TCUI"
Remove-TSGAppx -PackageName "Microsoft.MicrosoftSolitaireCollection" -FriendlyName "Microsoft Solitaire"
Remove-TSGAppx -PackageName "Microsoft.MixedReality.Portal"          -FriendlyName "Mixed Reality Portal"
Remove-TSGAppx -PackageName "Clipchamp.Clipchamp"                    -FriendlyName "Clipchamp"
Remove-TSGAppx -PackageName "microsoft.windowscommunicationsapps"    -FriendlyName "Mail and Calendar"
Remove-TSGAppx -PackageName "Microsoft.People"                       -FriendlyName "People App"
Remove-TSGAppx -PackageName "Microsoft.WindowsMaps"                  -FriendlyName "Windows Maps"
Remove-TSGAppx -PackageName "Microsoft.MSPaint"                      -FriendlyName "Paint 3D"
Remove-TSGAppx -PackageName "Microsoft.SkypeApp"                     -FriendlyName "Skype"
Remove-TSGAppx -PackageName "MicrosoftTeams"                         -FriendlyName "Teams Consumer"
Remove-TSGAppx -PackageName "Microsoft.YourPhone"                    -FriendlyName "Phone Link"
Remove-TSGAppx -PackageName "MicrosoftCorporationII.QuickAssist"     -FriendlyName "Quick Assist"
Remove-TSGAppx -PackageName "Microsoft.WindowsFeedbackHub"           -FriendlyName "Feedback Hub"
Remove-TSGAppx -PackageName "Microsoft.Todos"                        -FriendlyName "Microsoft To Do"
Remove-TSGAppx -PackageName "Microsoft.PowerAutomateDesktop"         -FriendlyName "Power Automate Desktop"
Remove-TSGAppx -PackageName "BytedancePte.TikTok"                    -FriendlyName "TikTok"

Set-TSGRegistry -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "ContentDeliveryAllowed"      -Value 0
Set-TSGRegistry -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "SubscribedContentEnabled"     -Value 0
Set-TSGRegistry -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "SystemPaneSuggestionsEnabled" -Value 0
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\CloudContent" -Name "DisableWindowsConsumerFeatures" -Value 1
Set-TSGRegistry -Path "HKCU:\SOFTWARE\Policies\Microsoft\Windows\CloudContent" -Name "DisableWindowsSpotlightFeatures" -Value 1
Write-Host "    [OK] All consumer apps and Start Menu ads removed" -ForegroundColor Green


# ================================================================================
# FINALIZATION
# ================================================================================
Write-TSGSection "FINALIZATION"

if ($SkippedEntControls.Count -gt 0) {
    Write-Host ""
    Write-Host "  Enterprise-only controls skipped on this Pro SKU:" -ForegroundColor Yellow
    $SkippedEntControls | ForEach-Object { Write-Host "    * $_" -ForegroundColor Yellow }
    Write-Host "  Source: learn.microsoft.com/windows/security/licensing-and-edition-requirements" -ForegroundColor DarkGray
}

Write-Host ""
Write-Host "  Kiosk lockdown complete." -ForegroundColor Cyan
Write-Host "  Log: $LogPath" -ForegroundColor White
Write-Host "  RESTART REQUIRED: DEP, LSA Protection, IPv6 disable, Credential Guard, BitLocker" -ForegroundColor Yellow
Write-Host ""
Write-Host "  POST-RESTART CHECKLIST:" -ForegroundColor White
Write-Host "    1. Launch the kiosk application and verify it starts correctly" -ForegroundColor DarkGray
Write-Host "    2. If CFA blocks the app: Add-MpPreference -ControlledFolderAccessAllowedApplications 'App.exe'" -ForegroundColor DarkGray
Write-Host "    3. Verify no firewall rules are blocking required connections" -ForegroundColor DarkGray
Write-Host "    4. Review C:\Logs\ for any [FAIL] entries and address them" -ForegroundColor DarkGray
Write-Host "  Hans Study | https://hans.study | contact@hans.study" -ForegroundColor DarkGray

$restart = Read-Host "  Restart now? [y/N]"
if ($restart -match '^[Yy]') {
    Write-Host "  Restarting in 15 seconds. Press Ctrl+C to cancel." -ForegroundColor Yellow
    Start-Sleep -Seconds 15
    Restart-Computer -Force
}

Stop-Transcript | Out-Null
