#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Applies a curated minimum security baseline to a Windows workstation.

.DESCRIPTION
    The controls that deliver the most security value with the least operational
    risk. Every control works on Windows 10/11 Pro without additional licensing
    and is extremely unlikely to break existing applications.

    Use this when:
      Hardening a legacy environment where compatibility is a concern
      You need a verified baseline before applying more comprehensive hardening
      You want to confirm each control works before adding more

    Apply CCCS-NSA-CISA-Baseline.ps1 for full coverage after this.

.NOTES
    ================================================================
    Study Workstation Configurator
    Template: Minimum Viable Security

    Generated by Hans Study, CISSP / TSG Labs
    Generated:          2026-05-16
    Config fingerprint: (curated baseline; not configurator output)

    Website:   https://hans.study
    Email:     contact@hans.study
    LinkedIn:  https://linkedin.com/in/hans-study
    Instagram: https://instagram.com/studybyt3s
    X:         https://x.com/studybyt3s
    YouTube:   https://youtube.com/@studybyt3s
    GitHub:    https://github.com/tsglabs

    Target OS:  Windows 10/11 Pro or Enterprise, Server 2019/2022/2025
    Version:    2.0

    STANDARDS REFERENCED:
      CSE/CCCS ITSP.70.012                    (cyber.gc.ca)
      NSA/CISA Cybersecurity Information Sheets (media.defense.gov)
      DISA STIG Windows 11 V2R2               (public.cyber.mil)
      CIS Microsoft Windows 11 Benchmark v3.0  (cisecurity.org)

    Source-available. Personal and internal use permitted.
    Redistribution requires written authorization from Hans Study.
    See LICENSE for full terms.
    Hans Study accepts no liability for unintended consequences.
    ================================================================
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = "Continue"

$LogDate = Get-Date -Format "yyyyMMdd"
$LogPath = "C:\Logs\Minimum-Viable-Security_$LogDate.log"
if (-not (Test-Path "C:\Logs")) { New-Item -ItemType Directory -Path "C:\Logs" -Force | Out-Null }
Start-Transcript -Path $LogPath -Append -IncludeInvocationHeader | Out-Null

$sharedModule = Join-Path $PSScriptRoot "TSG-Shared.psm1"
if (Test-Path $sharedModule) { . $sharedModule }
else {
    function Write-TSGSection { param([string]$Title, [string]$Subtitle = "")
        Write-Host ""; Write-Host "  == $Title" -ForegroundColor Yellow
        if ($Subtitle) { Write-Host "     $Subtitle" -ForegroundColor DarkGray }
    }
    function Set-TSGRegistry { param([string]$Path, [string]$Name, [object]$Value, [string]$Type = "DWord")
        try {
            if (-not (Test-Path $Path)) { New-Item -Path $Path -Force | Out-Null }
            Set-ItemProperty -Path $Path -Name $Name -Value $Value -Type $Type -Force -ErrorAction Stop
            Write-Host "    [OK] $($Path.Split('\')[-1])\$Name = $Value" -ForegroundColor Green
        } catch { Write-Host "    [FAIL] $Name -- $($_.Exception.Message)" -ForegroundColor Red }
    }
    function New-TSGRestorePoint { param([string]$Description = "Hardening")
        try { Checkpoint-Computer -Description "$Description $(Get-Date -Format 'yyyy-MM-dd')" -RestorePointType "MODIFY_SETTINGS" -ErrorAction Stop; Write-Host "  [OK] Restore point created" -ForegroundColor Green }
        catch { Write-Host "  [WARN] Restore point failed -- continuing" -ForegroundColor Yellow }
    }
}

Write-Host ""; Write-Host "  =========================================================" -ForegroundColor Cyan
Write-Host "  Minimum Viable Security" -ForegroundColor Cyan
Write-Host "  High-impact, low-disruption controls for any Windows system" -ForegroundColor White
Write-Host "  Hans Study, CISSP | https://hans.study" -ForegroundColor DarkGray
Write-Host "  Log: $LogPath" -ForegroundColor DarkGray
Write-Host "  =========================================================" -ForegroundColor Cyan; Write-Host ""

New-TSGRestorePoint -Description "Minimum Viable Security"

Write-TSGSection "CREDENTIAL PROTECTION" "The highest-impact controls -- zero restart, zero application risk"

# These three controls prevent credential theft with no operational impact.
# No legitimate application requires WDigest enabled, LM hashes stored,
# or NTLMv1 authentication.

# Disable WDigest -- prevents cleartext credentials in LSASS memory
# Source: DISA WN11-CC-000040 | CIS 18.9.29.1 | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\WDigest" -Name "UseLogonCredential" -Value 0

# Do not store LAN Manager hash
# Source: DISA WN11-SO-000190 | CIS 2.3.11.6 | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Lsa" -Name "NoLMHash" -Value 1

# Require NTLMv2 only (LmCompatibilityLevel 5 = refuse all LM and NTLMv1)
# Source: DISA WN11-SO-000195 | CIS 2.3.11.7 | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Lsa" -Name "LmCompatibilityLevel" -Value 5

# Enable LSA Protection -- works on all editions including Pro, restart required
# Source: DISA WN11-SO-000100 | CIS 18.3.2 | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Lsa" -Name "RunAsPPL" -Value 1
Write-Host "    [NOTE] Restart required for LSA Protection" -ForegroundColor Yellow


Write-TSGSection "NETWORK HARDENING" "No legacy protocol required by any modern system"

# Disable SMBv1 -- no modern system requires it, EternalBlue vector
# Source: DISA WN11-00-000160/165 | CIS 18.3.3 | NSA | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters" -Name "SMB1" -Value 0
Disable-WindowsOptionalFeature -Online -FeatureName "SMB1Protocol" -NoRestart -ErrorAction SilentlyContinue | Out-Null
Write-Host "    [OK] SMBv1 disabled" -ForegroundColor Green

# Remove PowerShell v2 -- bypasses all modern PS security features
# NSA/CISA June 2022 CSI explicitly requires this removal
# Source: DISA WN11-00-000155 | NSA/CISA June 2022 CSI | CCCS ITSP.70.012
Disable-WindowsOptionalFeature -Online -FeatureName "MicrosoftWindowsPowerShellV2Root" -NoRestart -ErrorAction SilentlyContinue | Out-Null
Write-Host "    [OK] PowerShell v2 removed" -ForegroundColor Green

# Disable LLMNR -- passive NTLMv2 hash capture with Responder/Inveigh
# Source: DISA WN11-CC-000085 | CIS 18.5.4 | NSA/CISA | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient" -Name "EnableMulticast" -Value 0

# Enable Windows Firewall on all profiles
# Source: DISA WN11-NX-000010/015/020 | CIS 9.1.1/9.2.1/9.3.1 | CCCS ITSP.70.012
Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled True
Write-Host "    [OK] Firewall enabled on all profiles" -ForegroundColor Green


Write-TSGSection "WINDOWS DEFENDER" "DISA WN11-00-000270/275"
Set-Service -Name "WinDefend" -StartupType Automatic -ErrorAction SilentlyContinue
Start-Service -Name "WinDefend" -ErrorAction SilentlyContinue
Set-MpPreference -DisableRealtimeMonitoring $false
Write-Host "    [OK] Windows Defender running with real-time protection" -ForegroundColor Green


Write-TSGSection "AUDIT AND LOGGING" "The minimum for incident response -- without these you cannot investigate"

# Logon events -- foundation of any incident investigation timeline
# Source: DISA WN11-AU-000030/035 | CIS 17.5.1 | CCCS ITSP.70.012
AuditPol /set /subcategory:"Logon"           /success:enable /failure:enable | Out-Null
AuditPol /set /subcategory:"Logoff"          /success:enable                 | Out-Null
AuditPol /set /subcategory:"Account Lockout" /failure:enable                 | Out-Null
Write-Host "    [OK] Logon/logoff auditing enabled" -ForegroundColor Green

# Process creation with command-line capture
# Without this, you cannot reconstruct what ran on the machine after an incident
# Source: DISA WN11-AU-000500/505 | NSA/CISA | CCCS ITSP.70.012
AuditPol /set /subcategory:"Process Creation" /success:enable | Out-Null
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Audit" -Name "ProcessCreationIncludeCmdLine_Enabled" -Value 1

# Increase Security log to 1GB -- 64MB fills in hours on any active system
# Source: DISA WN11-AU-000045 | CIS 18.9.26.1 | CCCS ITSP.70.012
wevtutil sl Security    /ms:1073741824 | Out-Null
wevtutil sl Application /ms:268435456  | Out-Null
wevtutil sl System      /ms:268435456  | Out-Null
Write-Host "    [OK] Security log increased to 1GB" -ForegroundColor Green

# PowerShell Script Block Logging -- highest-value PS security control
# Logs full deobfuscated PS content. NSA/CISA call this out as a priority.
# Source: DISA WN11-CC-000315 | NSA/CISA June 2022 CSI | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging" -Name "EnableScriptBlockLogging"         -Value 1
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging" -Name "EnableScriptBlockInvocationLogging" -Value 1
wevtutil sl "Microsoft-Windows-PowerShell/Operational" /ms:104857600 | Out-Null
Write-Host "    [OK] PowerShell Script Block Logging enabled" -ForegroundColor Green


Write-TSGSection "ACCESS CONTROL" "DISA WN11-SO-000245 | WN11-CC-000150 | CCCS ITSP.70.012"

# UAC enabled -- should never be disabled
# Source: DISA WN11-SO-000245 | CIS 2.3.17.1 | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" -Name "EnableLUA"            -Value 1
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" -Name "PromptOnSecureDesktop" -Value 1

# Disable AutoRun on all drive types
# Source: DISA WN11-CC-000150 | CIS 18.9.8.1 | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer" -Name "NoDriveTypeAutoRun" -Value 255
Set-TSGRegistry -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer" -Name "NoDriveTypeAutoRun" -Value 255

# Block Office macros from internet -- primary phishing delivery vector
# Source: DISA STIG | CIS | CCCS ITSP.70.012
$officeVersion = "16.0"
foreach ($app in @("Word", "Excel", "PowerPoint", "Outlook", "Access")) {
    Set-TSGRegistry -Path "HKCU:\SOFTWARE\Policies\Microsoft\Office\$officeVersion\$app\Security" -Name "VBAWarnings" -Value 4
}
Write-Host "    [OK] UAC, AutoRun, Office macros applied" -ForegroundColor Green


Write-TSGSection "TELEMETRY" "DISA WN11-CC-000206 | CCCS | NSA/CISA | PIPEDA"
Stop-Service -Name "DiagTrack" -ErrorAction SilentlyContinue
Set-Service  -Name "DiagTrack" -StartupType Disabled
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection" -Name "AllowTelemetry" -Value 0
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection" -Name "AllowTelemetry" -Value 0

# Disable Recall -- AI screenshot indexing of screen content
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsAI" -Name "DisableAIDataAnalysis" -Value 1
Set-TSGRegistry -Path "HKCU:\SOFTWARE\Policies\Microsoft\Windows\WindowsAI" -Name "DisableAIDataAnalysis" -Value 1
Disable-WindowsOptionalFeature -Online -FeatureName "Recall" -NoRestart -ErrorAction SilentlyContinue | Out-Null
Write-Host "    [OK] Telemetry and Recall disabled" -ForegroundColor Green


Write-TSGSection "EXPLOIT MITIGATION" "DISA WN11-00-000020/025 | CCCS ITSP.70.012"

# DEP -- marks data memory pages non-executable, restart required
# Source: DISA WN11-00-000020 | CIS 18.8.21.5 | NSA | CCCS ITSP.70.012
bcdedit /set nx AlwaysOn | Out-Null
Write-Host "    [OK] DEP set to AlwaysOn (restart required)" -ForegroundColor Green

# SEHOP -- value 0 ENABLES it (counterintuitive registry name, confirmed correct)
# Source: DISA WN11-00-000025 | CIS | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\kernel" -Name "DisableExceptionChainValidation" -Value 0


Write-TSGSection "FINALIZATION"
Write-Host ""
Write-Host "  Minimum Viable Security baseline applied." -ForegroundColor Cyan
Write-Host "  Log: $LogPath" -ForegroundColor White
Write-Host "  RESTART REQUIRED: DEP, LSA Protection" -ForegroundColor Yellow
Write-Host ""
Write-Host "  NEXT STEPS:" -ForegroundColor White
Write-Host "    Apply CCCS-NSA-CISA-Baseline.ps1 for comprehensive hardening." -ForegroundColor DarkGray
Write-Host "    Apply DISA-STIG-Baseline.ps1 for DoD-level hardening." -ForegroundColor DarkGray
Write-Host "  Hans Study | https://hans.study | contact@hans.study" -ForegroundColor DarkGray

$restart = Read-Host "  Restart now? [y/N]"
if ($restart -match '^[Yy]') { Write-Host "  Restarting..." -ForegroundColor Yellow; Start-Sleep -Seconds 15; Restart-Computer -Force }
Stop-Transcript | Out-Null
