#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Hardens a Windows workstation for security analyst, threat hunter, or DFIR use.

.DESCRIPTION
    DISA STIG-level hardening with analyst-specific carve-outs. Designed for SOC
    analysts, threat hunters, digital forensics practitioners, and incident
    responders who need a hardened-but-functional workstation.

    Deliberate differences from the standard DISA STIG template:
      IPv6 is LEFT ENABLED. Analysts test IPv6 attack paths and need it functional.
      RDP is LEFT ENABLED with NLA enforced. Remote lab access is operationally required.
      Cloud protection is DISABLED. Malware analysis and sandbox work must not send
        samples to Microsoft. Re-enable if air-gap work is not the use case.
      Controlled Folder Access is NOT enabled. Forensic tools, log aggregators, and
        custom scripts write to many locations. CFA would require constant whitelisting.
      Security event log is set to 2GB to handle high event volume from analyst tools.

.NOTES
    ================================================================
    Study Workstation Configurator
    Template: Security Analyst Workstation

    Generated by Hans Study, CISSP / TSG Labs
    Generated:          2026-05-16
    Config fingerprint: (curated baseline; not configurator output)

    Website:   https://hans.study
    Email:     contact@hans.study
    LinkedIn:  https://linkedin.com/in/hans-study
    Instagram: https://instagram.com/studybyt3s
    X:         https://x.com/studybyt3s
    YouTube:   https://youtube.com/@studybyt3s
    GitHub:    https://github.com/tsglabs

    Target OS:  Windows 10/11 Pro or Enterprise
    Version:    2.0

    STANDARDS REFERENCED:
      DISA STIG Windows 11 V2R2 / Windows 10 V2R7 (public.cyber.mil)
      CIS Microsoft Windows 11 Benchmark v3.0      (cisecurity.org)
      NSA/CISA Cybersecurity Information Sheets    (media.defense.gov)
      CSE/CCCS ITSP.70.012                         (cyber.gc.ca)

    Source-available. Personal and internal use permitted.
    Redistribution requires written authorization from Hans Study.
    See LICENSE for full terms.
    Test in a non-production environment before deployment.
    Hans Study accepts no liability for unintended consequences.
    ================================================================
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = "Continue"
$SkippedEntControls = [System.Collections.Generic.List[string]]::new()

$LogDate = Get-Date -Format "yyyyMMdd"
$LogPath = "C:\Logs\Security-Analyst-Workstation_$LogDate.log"
if (-not (Test-Path "C:\Logs")) { New-Item -ItemType Directory -Path "C:\Logs" -Force | Out-Null }
Start-Transcript -Path $LogPath -Append -IncludeInvocationHeader | Out-Null

$sharedModule = Join-Path $PSScriptRoot "TSG-Shared.psm1"
if (Test-Path $sharedModule) { . $sharedModule }
else {
    function Write-TSGSection { param([string]$Title, [string]$Subtitle = "")
        Write-Host ""; Write-Host "  == $Title" -ForegroundColor Yellow
        if ($Subtitle) { Write-Host "     $Subtitle" -ForegroundColor DarkGray }
    }
    function Set-TSGRegistry { param([string]$Path, [string]$Name, [object]$Value, [string]$Type = "DWord")
        try {
            if (-not (Test-Path $Path)) { New-Item -Path $Path -Force | Out-Null }
            Set-ItemProperty -Path $Path -Name $Name -Value $Value -Type $Type -Force -ErrorAction Stop
            Write-Host "    [OK] $($Path.Split('\')[-1])\$Name = $Value" -ForegroundColor Green
        } catch { Write-Host "    [FAIL] $Name -- $($_.Exception.Message)" -ForegroundColor Red }
    }
    function Remove-TSGAppx { param([string]$PackageName, [string]$FriendlyName)
        try {
            Get-AppxProvisionedPackage -Online -ErrorAction SilentlyContinue |
                Where-Object { $_.DisplayName -like "*$PackageName*" } |
                Remove-AppxProvisionedPackage -Online -ErrorAction SilentlyContinue | Out-Null
            Get-AppxPackage -AllUsers -ErrorAction SilentlyContinue |
                Where-Object { $_.Name -like "*$PackageName*" } |
                Remove-AppxPackage -AllUsers -ErrorAction SilentlyContinue
            Write-Host "    [OK] $FriendlyName removed or already absent" -ForegroundColor Green
        } catch { Write-Host "    [SKIP] $FriendlyName" -ForegroundColor DarkGray }
    }
    function Test-TSGEnterprise { param([string]$ControlName = "This control")
        $sku = (Get-CimInstance Win32_OperatingSystem).OperatingSystemSKU
        if ($sku -in @(4,27,70,84,125,161,162,163,164,169,170,171,172)) { return $true }
        Write-Host "    [SKIP] $ControlName requires Enterprise license (SKU: $sku)" -ForegroundColor Yellow
        $script:SkippedEntControls.Add($ControlName); return $false
    }
    function New-TSGRestorePoint { param([string]$Description = "Hardening")
        try { Checkpoint-Computer -Description "$Description $(Get-Date -Format 'yyyy-MM-dd')" -RestorePointType "MODIFY_SETTINGS" -ErrorAction Stop
              Write-Host "  [OK] Restore point created" -ForegroundColor Green }
        catch { Write-Host "  [WARN] Restore point failed -- continuing" -ForegroundColor Yellow }
    }
    function Disable-TSGNetBIOS {
        try {
            $adapters = Get-WmiObject -Class Win32_NetworkAdapterConfiguration -Filter "IPEnabled = True"
            foreach ($a in $adapters) { $a.SetTcpipNetbios(2) | Out-Null }
            Write-Host "    [OK] NetBIOS over TCP/IP disabled on all adapters" -ForegroundColor Green
        } catch { Write-Host "    [FAIL] $($_.Exception.Message)" -ForegroundColor Red }
    }
}

Write-Host ""
Write-Host "  =========================================================" -ForegroundColor Cyan
Write-Host "  Security Analyst Workstation Hardening" -ForegroundColor Cyan
Write-Host "  SOC / Threat Hunt / DFIR -- DISA STIG + analyst carve-outs" -ForegroundColor White
Write-Host "  Hans Study, CISSP | https://hans.study" -ForegroundColor DarkGray
Write-Host "  Log: $LogPath" -ForegroundColor DarkGray
Write-Host "  =========================================================" -ForegroundColor Cyan
Write-Host ""

$OsSku = (Get-CimInstance Win32_OperatingSystem).OperatingSystemSKU
$IsEnterprise = $OsSku -in @(4,27,70,84,125,161,162,163,164,169,170,171,172)
Write-Host "  OS SKU: $OsSku | Edition: $(if ($IsEnterprise) { 'Enterprise/Server' } else { 'Pro' })" `
    -ForegroundColor $(if ($IsEnterprise) { "Green" } else { "Yellow" })
Write-Host ""

New-TSGRestorePoint -Description "Security Analyst Workstation"


# ================================================================================
# CREDENTIAL AND IDENTITY PROTECTION
# Source: DISA WN11-CC-000040 | WN11-SO-000100/190/195 | WN11-00-000095
# ================================================================================
Write-TSGSection "CREDENTIAL AND IDENTITY PROTECTION" "DISA WN11-CC-000040 | WN11-SO-000100/190/195 | WN11-00-000095"

# Disable WDigest -- prevents cleartext credentials in LSASS memory
# Source: DISA WN11-CC-000040 | CIS 18.9.29.1 | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\WDigest" -Name "UseLogonCredential" -Value 0

# Do not store LAN Manager hash
# Source: DISA WN11-SO-000190 | CIS 2.3.11.6 | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Lsa" -Name "NoLMHash" -Value 1

# Require NTLMv2 only (LmCompatibilityLevel 5 = refuse all LM and NTLMv1)
# Source: DISA WN11-SO-000195 | CIS 2.3.11.7 | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Lsa" -Name "LmCompatibilityLevel" -Value 5

# Enable LSA Protection (RunAsPPL) -- all editions, restart required
# Source: DISA WN11-SO-000100 | CIS 18.3.2 | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Lsa" -Name "RunAsPPL" -Value 1
Write-Host "    [NOTE] Restart required for LSA Protection" -ForegroundColor Yellow

# Credential Guard -- Enterprise/Education only
# Source: DISA WN11-00-000095 | NSA/CISA | CCCS ITSP.70.012
if (Test-TSGEnterprise -ControlName "Credential Guard (WN11-00-000095)") {
    Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\DeviceGuard" -Name "EnableVirtualizationBasedSecurity" -Value 1
    Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\DeviceGuard" -Name "RequirePlatformSecurityFeatures" -Value 3
    Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\DeviceGuard\Scenarios\CredentialGuard" -Name "Enabled" -Value 1
    Write-Host "    [NOTE] Restart required for Credential Guard" -ForegroundColor Yellow
}


# ================================================================================
# NETWORK HARDENING
# Source: DISA WN11-00-000155/160/165 | WN11-CC-000080/085 | WN11-NX | WN11-SO-000160/165
# ================================================================================
Write-TSGSection "NETWORK HARDENING" "DISA WN11-00-000155/160/165 | WN11-CC-000080/085 | WN11-NX"

# Disable SMBv1
# Source: DISA WN11-00-000160/165 | CIS 18.3.3 | NSA | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters" -Name "SMB1" -Value 0
Disable-WindowsOptionalFeature -Online -FeatureName "SMB1Protocol" -NoRestart -ErrorAction SilentlyContinue | Out-Null
Write-Host "    [OK] SMBv1 disabled" -ForegroundColor Green

# Remove PowerShell v2
# Source: DISA WN11-00-000155 | NSA/CISA June 2022 CSI | CCCS ITSP.70.012
Disable-WindowsOptionalFeature -Online -FeatureName "MicrosoftWindowsPowerShellV2Root" -NoRestart -ErrorAction SilentlyContinue | Out-Null
Write-Host "    [OK] PowerShell v2 removed" -ForegroundColor Green

# Disable LLMNR
# Source: DISA WN11-CC-000085 | CIS 18.5.4 | NSA/CISA | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient" -Name "EnableMulticast" -Value 0

# Disable NetBIOS over TCP/IP
# Source: DISA WN11-CC-000080 | NSA | CCCS ITSP.70.012
Disable-TSGNetBIOS

# Windows Firewall -- all profiles, default-deny inbound
# Source: DISA WN11-NX-000010/015/020/025/030/035 | CIS 9.x | CCCS ITSP.70.012
Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled True
Set-NetFirewallProfile -Profile Domain,Public,Private -DefaultInboundAction Block
Write-Host "    [OK] Firewall enabled, default-deny inbound" -ForegroundColor Green

# Require SMB packet signing
# Source: DISA WN11-SO-000160/165 | CIS 2.3.9.1/2.3.9.2 | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters" -Name "RequireSecuritySignature" -Value 1
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters" -Name "RequireSecuritySignature" -Value 1

# IPv6 intentionally LEFT ENABLED
# Analysts frequently test IPv6 attack paths and need the stack functional.
# Disabling it would break dual-stack lab environments, IPv6 scanning, and
# tooling that binds to IPv6 interfaces.
Write-Host "    [NOTE] IPv6 intentionally left enabled -- required for analyst workflows" -ForegroundColor Yellow


# ================================================================================
# WINDOWS DEFENDER -- ANALYST CONFIGURATION
# Source: DISA WN11-00-000270/275
# ================================================================================
Write-TSGSection "WINDOWS DEFENDER -- ANALYST CONFIGURATION" "DISA WN11-00-000270/275"

Set-Service -Name "WinDefend" -StartupType Automatic -ErrorAction SilentlyContinue
Start-Service -Name "WinDefend" -ErrorAction SilentlyContinue
Set-MpPreference -DisableRealtimeMonitoring $false
Set-MpPreference -EnableNetworkProtection Enabled

# Disable cloud-delivered protection
# Malware samples and sandbox work must not submit to Microsoft cloud infrastructure.
# This prevents accidental sample exfiltration from isolated analysis environments.
# Re-enable if the workstation is NOT used for malware analysis.
Set-MpPreference -MAPSReporting Disabled
Set-MpPreference -SubmitSamplesConsent NeverSend
Write-Host "    [OK] Defender running, cloud protection disabled (analysis/sandbox mode)" -ForegroundColor Green
Write-Host "    [NOTE] Remove the MAPS/SubmitSamples block if this is not a malware analysis workstation" -ForegroundColor Yellow

# Controlled Folder Access intentionally NOT enabled
# Forensic tools, memory analysis utilities, log parsers, and custom scripts
# write to many locations. CFA would need extensive whitelisting before being
# usable. If you want it, start with AuditMode and build the allowlist over 30 days.
Write-Host "    [NOTE] CFA not enabled -- analyst tool compatibility" -ForegroundColor Yellow


# ================================================================================
# AUDIT POLICY AND LOGGING -- MAXIMUM COVERAGE
# Analysts generate high event volume. All categories enabled, logs sized up.
# Source: DISA WN11-AU | NSA/CISA June 2022 CSI | CCCS ITSP.70.012
# ================================================================================
Write-TSGSection "AUDIT POLICY AND LOGGING -- MAXIMUM COVERAGE" "DISA WN11-AU-000010 through WN11-AU-000560"

# Core audit categories (all verified auditpol subcategory names)
AuditPol /set /subcategory:"Logon"                   /success:enable /failure:enable | Out-Null
AuditPol /set /subcategory:"Logoff"                  /success:enable                 | Out-Null
AuditPol /set /subcategory:"Account Lockout"         /failure:enable                 | Out-Null
AuditPol /set /subcategory:"Credential Validation"   /success:enable /failure:enable | Out-Null
AuditPol /set /subcategory:"Process Creation"        /success:enable                 | Out-Null
AuditPol /set /subcategory:"Sensitive Privilege Use" /success:enable /failure:enable | Out-Null
AuditPol /set /subcategory:"Audit Policy Change"     /success:enable /failure:enable | Out-Null
AuditPol /set /subcategory:"File System"             /success:enable /failure:enable | Out-Null
AuditPol /set /subcategory:"Registry"                /success:enable /failure:enable | Out-Null
AuditPol /set /subcategory:"Kernel Object"           /success:enable /failure:enable | Out-Null
AuditPol /set /subcategory:"User Account Management" /success:enable /failure:enable | Out-Null
AuditPol /set /subcategory:"Special Logon"           /success:enable                 | Out-Null
Write-Host "    [OK] Maximum audit coverage configured" -ForegroundColor Green

# Process creation with command-line capture -- both pieces required
# Source: DISA WN11-AU-000500/505 | NSA/CISA | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Audit" -Name "ProcessCreationIncludeCmdLine_Enabled" -Value 1

# Security log set to 2GB -- analysts run many tools and generate high event volume
# Source: DISA WN11-AU-000045 | CIS 18.9.26.1 | CCCS ITSP.70.012
wevtutil sl Security    /ms:2147483648 | Out-Null   # 2 GB -- analysts need the headroom
wevtutil sl Application /ms:268435456  | Out-Null   # 256 MB
wevtutil sl System      /ms:268435456  | Out-Null   # 256 MB
Write-Host "    [OK] Log sizes: Security 2GB, Application/System 256MB" -ForegroundColor Green

# PowerShell Script Block Logging
# Source: DISA WN11-CC-000315 | NSA/CISA June 2022 CSI | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging" -Name "EnableScriptBlockLogging"         -Value 1
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging" -Name "EnableScriptBlockInvocationLogging" -Value 1
# PS Operational log at 200MB -- analysts run many scripts and need the retention
wevtutil sl "Microsoft-Windows-PowerShell/Operational" /ms:209715200 | Out-Null  # 200 MB
Write-Host "    [OK] PS Script Block Logging enabled (PS Operational log: 200MB)" -ForegroundColor Green

# PowerShell Transcription
# Source: NSA/CISA June 2022 CSI | CCCS | DISA WN11-CC-000326
$transcriptPath = "C:\Logs\PSTranscripts"
if (-not (Test-Path $transcriptPath)) { New-Item -ItemType Directory -Path $transcriptPath -Force | Out-Null }
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\Transcription" -Name "EnableTranscripting"    -Value 1
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\Transcription" -Name "OutputDirectory"        -Value $transcriptPath -Type String
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\Transcription" -Name "EnableInvocationHeader" -Value 1
Write-Host "    [OK] PS Transcription enabled -- output to $transcriptPath" -ForegroundColor Green


# ================================================================================
# ACCESS CONTROL
# Source: DISA WN11-SO-000245/251 | WN11-CC-000030/150 | CCCS ITSP.70.012
# ================================================================================
Write-TSGSection "ACCESS CONTROL" "DISA WN11-SO-000245/251 | WN11-CC-000030/150"

# UAC -- Always Notify (max level)
# Source: DISA WN11-SO-000245/251 | CIS 2.3.17.1/2 | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" -Name "EnableLUA"                 -Value 1
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" -Name "PromptOnSecureDesktop"      -Value 1
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" -Name "ConsentPromptBehaviorAdmin" -Value 2

# Disable AutoRun on all drive types (NoDriveTypeAutoRun = 255 = all types)
# Source: DISA WN11-CC-000150 | CIS 18.9.8.1 | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer" -Name "NoDriveTypeAutoRun" -Value 255
Set-TSGRegistry -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer" -Name "NoDriveTypeAutoRun" -Value 255

# RDP intentionally LEFT ENABLED -- analysts need remote access to lab machines
# NLA enforced: credentials required before session establishment
# Source: DISA WN11-CC-000030 | CIS 18.9.59.2.1 | CCCS
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "UserAuthentication" -Value 1
Write-Host "    [OK] RDP left enabled -- NLA enforced, required for lab remote access" -ForegroundColor Green

# Restrict PowerShell execution policy to RemoteSigned
# Source: NSA/CISA June 2022 CSI | CCCS ITSP.70.012
Set-ExecutionPolicy RemoteSigned -Scope LocalMachine -Force

# Block Office macros from internet sources
# Source: DISA STIG | CIS | CCCS ITSP.70.012
$officeVersion = "16.0"
foreach ($app in @("Word", "Excel", "PowerPoint", "Outlook", "Access")) {
    Set-TSGRegistry -Path "HKCU:\SOFTWARE\Policies\Microsoft\Office\$officeVersion\$app\Security" -Name "VBAWarnings" -Value 4
}
Write-Host "    [OK] Access control applied" -ForegroundColor Green


# ================================================================================
# TELEMETRY AND PRIVACY
# Source: DISA WN11-CC-000010/206/225 | NSA/CISA | CCCS | PIPEDA
# ================================================================================
Write-TSGSection "TELEMETRY AND PRIVACY" "DISA WN11-CC-000010/206/225"

Stop-Service -Name "DiagTrack" -ErrorAction SilentlyContinue
Set-Service  -Name "DiagTrack" -StartupType Disabled
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection" -Name "AllowTelemetry" -Value 0
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection" -Name "AllowTelemetry" -Value 0
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\System" -Name "PublishUserActivities" -Value 0
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\System" -Name "UploadUserActivities"  -Value 0
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsAI" -Name "DisableAIDataAnalysis" -Value 1
Set-TSGRegistry -Path "HKCU:\SOFTWARE\Policies\Microsoft\Windows\WindowsAI" -Name "DisableAIDataAnalysis" -Value 1
Disable-WindowsOptionalFeature -Online -FeatureName "Recall" -NoRestart -ErrorAction SilentlyContinue | Out-Null
Set-TSGRegistry -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\AdvertisingInfo" -Name "Enabled" -Value 0
Write-Host "    [OK] Telemetry, Activity History, Recall, Advertising ID disabled" -ForegroundColor Green


# ================================================================================
# EXPLOIT MITIGATION
# Source: DISA WN11-00-000020/025 | CIS 18.8.21.5 | NSA | CCCS ITSP.70.012
# ================================================================================
Write-TSGSection "EXPLOIT MITIGATION" "DISA WN11-00-000020/025 | CIS 18.8.21.5 | NSA"

# DEP AlwaysOn -- restart required
# Source: DISA WN11-00-000020 | CIS 18.8.21.5 | NSA | CCCS ITSP.70.012
bcdedit /set nx AlwaysOn | Out-Null
Write-Host "    [OK] DEP set to AlwaysOn (restart required)" -ForegroundColor Green

# ASLR with forced relocation
# Source: CIS | NSA | CCCS ITSP.70.012
Set-ProcessMitigation -System -Enable ASLR,ForceRelocateImages -ErrorAction SilentlyContinue
Write-Host "    [OK] ASLR and forced relocation enabled" -ForegroundColor Green

# SEHOP -- value 0 ENABLES it (counterintuitive name, confirmed in DISA WN11-00-000025)
# Source: DISA WN11-00-000025 | CIS | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\kernel" -Name "DisableExceptionChainValidation" -Value 0

# Disable hibernation
# Source: NSA | CCCS ITSP.70.012
powercfg -h off
Write-Host "    [OK] Hibernation disabled, hiberfil.sys removed" -ForegroundColor Green


# ================================================================================
# BLOATWARE REMOVAL
# ================================================================================
Write-TSGSection "BLOATWARE REMOVAL" "Least functionality | DISA CM controls"

Remove-TSGAppx -PackageName "Microsoft.549981C3F5F10"                -FriendlyName "Cortana"
Remove-TSGAppx -PackageName "Microsoft.Windows.Copilot"              -FriendlyName "Windows Copilot"
Remove-TSGAppx -PackageName "MicrosoftWindows.Client.WebExperience"  -FriendlyName "Windows Widgets"
Remove-TSGAppx -PackageName "Microsoft.BingNews"                     -FriendlyName "Bing News"
Remove-TSGAppx -PackageName "Microsoft.BingWeather"                  -FriendlyName "Bing Weather"
Remove-TSGAppx -PackageName "Microsoft.GamingApp"                    -FriendlyName "Xbox Gaming App"
Remove-TSGAppx -PackageName "Microsoft.XboxApp"                      -FriendlyName "Xbox App"
Remove-TSGAppx -PackageName "Microsoft.XboxGameOverlay"              -FriendlyName "Xbox Game Overlay"
Remove-TSGAppx -PackageName "Microsoft.XboxGamingOverlay"            -FriendlyName "Xbox Gaming Overlay"
Remove-TSGAppx -PackageName "Microsoft.MicrosoftSolitaireCollection" -FriendlyName "Microsoft Solitaire"
Remove-TSGAppx -PackageName "Microsoft.YourPhone"                    -FriendlyName "Phone Link"
Remove-TSGAppx -PackageName "Microsoft.SkypeApp"                     -FriendlyName "Skype"
Remove-TSGAppx -PackageName "MicrosoftTeams"                         -FriendlyName "Teams Consumer"
Remove-TSGAppx -PackageName "Clipchamp.Clipchamp"                    -FriendlyName "Clipchamp"
Remove-TSGAppx -PackageName "BytedancePte.TikTok"                    -FriendlyName "TikTok"

Set-TSGRegistry -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "ContentDeliveryAllowed"      -Value 0
Set-TSGRegistry -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "SubscribedContentEnabled"     -Value 0
Set-TSGRegistry -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "SystemPaneSuggestionsEnabled" -Value 0
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\CloudContent" -Name "DisableWindowsConsumerFeatures" -Value 1
Set-TSGRegistry -Path "HKCU:\SOFTWARE\Policies\Microsoft\Windows\CloudContent" -Name "DisableWindowsSpotlightFeatures" -Value 1
Write-Host "    [OK] Consumer apps and Start Menu ads removed" -ForegroundColor Green


# ================================================================================
# FINALIZATION
# ================================================================================
Write-TSGSection "FINALIZATION"

if ($SkippedEntControls.Count -gt 0) {
    Write-Host ""
    Write-Host "  Enterprise-only controls skipped on this Pro SKU:" -ForegroundColor Yellow
    $SkippedEntControls | ForEach-Object { Write-Host "    * $_" -ForegroundColor Yellow }
    Write-Host "  Source: learn.microsoft.com/windows/security/licensing-and-edition-requirements" -ForegroundColor DarkGray
}

Write-Host ""
Write-Host "  Security Analyst workstation hardening complete." -ForegroundColor Cyan
Write-Host "  Log: $LogPath" -ForegroundColor White
Write-Host "  RESTART REQUIRED: DEP, LSA Protection, Credential Guard" -ForegroundColor Yellow
Write-Host "  Hans Study | https://hans.study | contact@hans.study" -ForegroundColor DarkGray

$restart = Read-Host "  Restart now? [y/N]"
if ($restart -match '^[Yy]') {
    Write-Host "  Restarting in 15 seconds. Press Ctrl+C to cancel." -ForegroundColor Yellow
    Start-Sleep -Seconds 15
    Restart-Computer -Force
}

Stop-Transcript | Out-Null
